### PR TITLE
Feature/auto close dropdown menu on contextmenu event

### PR DESCRIPTION
**Pull request by mboughaba**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by benouat** [comment]
@mboughaba main concern about your PR is that we are in the process of completely refactor (via #2727) the way `autoclose` feature is working all over the place. There is still a lot of work to be tackle down for #2727 to land in master, notably moving a lot of unit tests to their e2e equivalent in order to make it much more maintainable and easier to reason about.

At this point you might ask yourself "_Why is it related about my `contextmenu` PR?_", and this is a perfectly valid question!

Answer is that #2727 will change the way we listen to mouse events for `autoclose`. We will move from listening from `click` events to `mouseup` (or even `mousedown`) on which we will now have to way to use `event.button` giving us the information of which mouse button has been clicked (this info is not available on `click`). We will then have a proper way to close on left and right click.

That leads us to the conclusion that your PR, here, might not be needed at all.

Sorry for that. let's wait and see. Should not take us long to do all steps I previously listed.
I'll ping @pkozlowski-opensource  and @divdavem to see here if we are in sync.

**Comment by mboughaba** [comment]
Makes so much sense indeed. I will follow #2727 to see if there is anything I could contribute to.

**Comment by maxokorokov** [comment]
@mboughaba FYI the `AutoClose` service has landed finally, but current behaviour by default actually **does NOT close** the popups in question on the right click → tooltip, popover, dropdown, typeahead and datepicker. For compatibility reasons for tooltip, popover and dropdown.

I think just changing the behaviour to the opposite won't be a solution. So we should find a workaround/configurable solution (if you still need this) and continue discussion in #2765

**Pull request closed without merging**
