### PR TITLE
Add note about making ng-bootstrap work with Bootstrap 3

### PR DESCRIPTION
**Pull request by trumbitta**
I'm working on a CSS-based compatibility patch to make ng-bootstrap work with Bootstrap 3, because I need it at work.

I figured I could possibly not be the only one needing it, so I published it on NPM and will update it as I go on and find myself in need of more components.

This pull-request is really just a way to let you guys know about it.

## Current status:

- [x] Accordion *(BS4 structure with BS3 colors and spacing)*
- [ ] Alert
- [ ] Buttons
- [ ] Carousel
- [x] Collapse
- [ ] Datepicker
- [x] Dropdown
- [x] Modal
- [ ] Pagination
- [x] Popover
- [x] Progressbar
- [x] Rating *(It just works, no need for a patch)*
- [ ] Scrollspy *(Planned feature of ng-bootstrap)*
- [x] Tabs
- [ ] Timepicker
- [ ] Tooltip
- [x] Typeahead

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@trumbitta thnx for this. How far ahead are you in the project? Do you cover all the widgets?

Now, our stance with regards to Bootstrap 3 was this: we believe that starting new projects on Bootstrap 3 right now is waste of time. This is based on the fact that Bootstrap 3 is pretty much frozen an not evolving. As such people will have to migrate to Bootstrap 4 in the near future. But we believe that at this point migration from BS3 -> BS4 would cost more as compared to BS4.alpha -> BS4.final.

I will keep this PR open and keep an eye on your project / BS evolution and decide on merging based on how things evolve.

Once again, thnx for your work and letting us know, we love all the contributions!

**Comment by trumbitta** [comment]
@pkozlowski-opensource thanks for the feedback :) I already cover Collapse, Dropdown, Modal, and Typeahead. More will come in the near future, and my final goal is 100% coverage.

I'm doing this because at work I have a AngularJS + Bootstrap 3 application which I'm porting to Angular leveraging the UpgradeAdapter.  
Right now we can only afford to update the JS part, so the HTML and CSS will remain Bootstrap 3 for a while.

I agree 100% with your reasoning about the choice between BS3 and BS4 for ng-bootstrap; but I also think few companies would want to start a project using the alpha version of a CSS framework, so there's that.

Thanks again! I can come back to this PR and drop a line whenever I have a new component covered, if you are ok with that.

**Comment by Phmager** [comment]
> Now, our stance with regards to Bootstrap 3 was this: we believe that starting new projects on Bootstrap 3 right now is waste of time. This is based on the fact that Bootstrap 3 is pretty much frozen an not evolving. As such people will have to migrate to Bootstrap 4 in the near future. But we believe that at this point migration from BS3 -> BS4 would cost more as compared to BS4.alpha -> BS4.final.

We thought so too at first. But we went back from BS4 to BS3, because BS4 is still quite buggy and there are only view good admin templates out there for it.

**Comment by trumbitta** [comment]
Just added: Progressbars

**Comment by pkozlowski-opensource** [comment]
So, almost one year later things have changed a bit...:
* Bootstrap 4.x is stable
* ng-bootstrap hit stable 1.0 just today
* https://github.com/ngTrumbitta/ng-bootstrap-to-bootstrap-3 doesn't seem to be actively maintained 

Given all this I'm going to close this PR without merging. As a reminder, our stance on Bootstrap 4 is spelled out here: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F

**Comment by trumbitta** [comment]
Yep, I since switched to Bootstrap 4. Thanks for keeping this open all this time!

**Pull request closed without merging**
