### PR TITLE
fix(datepicker): IE11 visual improvements

### PR DESCRIPTION
**Pull request by gpolychronis**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by gpolychronis** [comment]
@maxokorokov Please review

**Comment by benouat** [comment]
**Side note**: please try to use Github syntax to link issues from description and git commit message. Such as the one below

Fixes #3690

**Comment by gpolychronis** [comment]
> 
> 
> Could you please explain how _playing around with flex_ is related to gaining focus back ?
> I believe it might fix something, I am not arguing that, I am just trying to understand.

In latest version I haven't noticed any problem with restoring focus. The only problem present is how input datepicker is displayed.

**Comment by benouat** [comment]
@gpolychronis In order for this PR to move on, could you re-open an another PR containing these changes, but name it differently and not associated with #3690 as it is clearly not related to me...
I propose `fix(datepicker): IE11 visual improvements` as title and commits message.

It would be nice also, if you could put screenshots of before and after the fix, so we could assess it properly. thanks.

**Comment by gpolychronis** [comment]
Screenshot_14

How it is displayed before the fix

**Comment by gpolychronis** [comment]
@benouat Pull Request has been updated.

**Comment by gpolychronis** [comment]
> 
> 
> I have one more request to address before moving on here 😅
> 
> Could you check IE11 on bootstrap itself for this kind of markup construct ?
> Maybe we did something wrong in our markup, because input groups are standards, and such an issue on IE11 would be huge on bootstrap side.
> 
> Thus my guts are telling me that these changes are not "normal" ones. We shouldn't have to add this extra CSS code.
> 
> I am sure we are missing something... let's find out what.

Screenshot_15

It's a bootstrap problem/ Shall we update to latest bootstrap (4.5) to fix ie?

**Comment by benouat** [comment]
> It's a bootstrap problem/ Shall we update to latest bootstrap (4.5) to fix ie?

Do you mean it has been fixed in 4.5 ?

**Comment by gpolychronis** [comment]
> 
> 
> > It's a bootstrap problem/ Shall we update to latest bootstrap (4.5) to fix ie?
> 
> Do you mean it has been fixed in 4.5 ?

yes

**Comment by benouat** [comment]
Flagging as won't merge, but keeping it to remind us about it.

**Comment by benouat** [comment]
Bootstrap 4.5.0 landed with #3797

**Pull request closed without merging**
