### PR TITLE
feat: upgrade to angular to v12

### LINKED ISSUE #4093: Angular 12 support
### Feature description:
[Angular 12](https://github.com/angular/angular/releases/tag/12.0.0) is released & I have successfully upgraded one of my small project using ng-bootstrap `9.1.1` & Angular `12.0.0`, but having official support would be good & Thank you for this great library.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12.0.0

ng-bootstrap: 9.1.1

Bootstrap: 4.6.0

### PR DESCRIPTION
**Pull request by internalsystemerror**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

This PR upgrades the minimum compatible dependencies to use Angular 12. You may wish to upgrade other dependencies too, however I was having issues testing different combinations and these are what proved to be the minimum that allowed tests to pass. Feel free to take control of this PR/branch etc as needed.

Closes #4093

### CODE REVIEW

**Comment by internalsystemerror** [comment]
Since it's been a month I thought I'd come back and rebase everything accordingly.

A quick summary of the actions taken in this PR:

Update angular to v12 (including @schematics/angular)
Update nguniversal to v12
Update ngx-build-plus to v12
Update commitlint to v12 (due to angular-config)
Update webpack to v5 (due to new peer dependency requirements)
Add line to README.md to mention v10 requiring Angular 12
Fix deprecation in schematic
Perform safe dependency upgrade to latest versions (yarn upgrade)

**Comment by internalsystemerror** [comment]
@maxokorokov can we get this reviewed, or can you at least approve the workflow so I can address any CI issues? Tests pass locally and I believe this should be RTM.

**Comment by terencehonles** [comment]
@fbasso do you mind approving this workflow? Quickly reviewing this code it looks like this is the appropriate change. I'm not sure if @maxokorokov is tied up, but we're already at Angular 12.1 and this should be released so people can upgrade without forcing the change. I've been running on Angular 12 so I can confirm it's at least not horribly broken :sweat_smile: and that the features I use work as expected.

@internalsystemerror I doubt it makes a difference, but since Angular 12.1 was released last week you might as well update this to that since it looks like there's been some lag in getting updates out recently.

**Comment by internalsystemerror** [comment]
@terencehonles tx, I've been keeping this updated periodically, I will update to use 12.1 when I get get chance (hopefully tonight)

**Review by maxokorokov — APPROVED** [review]
LGTM, thanks!

Sorry, I was away for a long time.

I've just fixed a small linting issue that failed the build and squashed the dependencies updates to remove noise.

Cheers,
Max

**Comment by internalsystemerror** [comment]
@maxokorokov you have my thanks

**Pull request merged**
