### PR TITLE
test(datepicker): get same date when period is not a NgbPeriod type

### PR DESCRIPTION
**Pull request by YisusW**
- [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by YisusW** [comment]
Screenshot from 2021-09-04 15-14-14


this unit test pass the line 36 in this unit test.

we expect the same date that we sent.

**Comment by YisusW** [comment]
@pkozlowski-opensource  

can i add unit test to this repo in this way?

**Comment by YisusW** [comment]
@maxokorokov can you review this change please?

**Review by maxokorokov — APPROVED** [review]
Thanks, @YisusW!

**Pull request merged**
