### PR TITLE
fix(datepicker): disabled date picker is clickable/focusable #3648

### PR DESCRIPTION
**Pull request by Smoggy**
Issue #3648[](https://github.com/ng-bootstrap/ng-bootstrap/issues/3648)

### CODE REVIEW

**Comment by fbasso** [comment]
Thanks for the PR @Smoggy 

Using the pointer-event seems to be the more natural and easy fix to do. But unfortunately it is not supported by IE10 : https://caniuse.com/#feat=pointer-events

I guess that this point is a problem.

**Comment by maxokorokov** [comment]
@fbasso good catch, I wasn't thinking about it. However do you have any ideas for a better solution? 

I think others will involve adding JS handlers/code just to support this use case in IE10. This one costs nothing and improves for most browsers. I think I personally would prefer to keep this one, unless there is another simple one that works everywhere.

**Comment by fbasso** [comment]
@maxokorokov, I agree. I think this css property must be kept anyway, it will have the priority on javascript behavior that we would (possibly, if someone complains about it) implement for ie10.

I don't know if ie10 is used a lot, as users usually have ie11 on their machine (automatically installed).

So I would go for this solution, and wait to see if someone complains for ie10.

**Comment by maxokorokov** [comment]
I pushed an e2e test here, will merge when green

**Pull request merged**
