### PR TITLE
feat(carousel): make getSlideIdxById public

### PR DESCRIPTION
**Pull request by wesleycho**
- Make `getSlideIdxbyId` a public method for easier programmatic selection of slides with the carousel

This should address #802

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@wesleycho I would like to dig a bit deeper into this one when back from AC

**Comment by pkozlowski-opensource** [comment]
@wesleycho I've just checked the PR and I think that there is some confusion here. The thing is that the `select` method gets slide identifier as an argument and _not_ the index. I think this is the good API.

But I think I know from where the confusion steams from! We've got good documentation:
> Navigate to a slide with a specified identifier.

but the method signature is misleading: `select(slideIdx: string)`. We should change it to `select(slideId: string)`.

Provided that the `select` method takes a string equals to slide id (and not index) do you think that you've got all the APIs you need? Or do we still miss things?

**Comment by wesleycho** [comment]
Oh, if that's the case then yeah, we don't need this public.

**Comment by wesleycho** [comment]
Closing this as unneeded

**Pull request closed without merging**
