### PR TITLE
feat(popover): allow a custom css class to be added

### LINKED ISSUE #1441: Allow or add option to bind user-defined class to Popover host
### Bug description:

Currently there is not way to add a user-defined class to the popover host.

Allowing to add user-defined class make life easier to customize (styling) the popover content as needed otherwise it will be patch work to to change the popover appearance.

We can style the popover content but not the popover itself. Its not a good idea to alter the popover globally so allowing to bind the custom class make life easy. 

### Link to minimally-working plunker that reproduces the issue:
[Plunker](http://plnkr.co/edit/ZVh3vSwb5DBfuA2IFyiY?p=preview)

### Version of Angular, ng-bootstrap, and Bootstrap: 

Angular: V-4

ng-bootstrap: 1.0.0-alpha.22

Bootstrap: 4.0.0-alpha.6

custom-view

### PR DESCRIPTION
**Pull request by mattlewis92**
Closes #1441

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by mattlewis92** [comment]
@pkozlowski-opensource is there anything I can do to help progress this PR? I'm currently having to maintain a fork to support this feature which is a PITA 😄

**Comment by AhmadZeid10** [comment]
Could you tell me where to add popoverClass in order to let popover take css style

**Comment by mattlewis92** [comment]
For anyone that wants this functionality today, I've written this directive which augments the existing ng-bootstrap popover. Just include it in the declarations of the module which imports the NgbPopover module.

```
import {
  Directive,
  Input,
  OnDestroy,
  Renderer2,
  AfterViewChecked,
  ElementRef
} from '@angular/core';
import { NgbPopover } from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import { Subscription } from 'rxjs/Subscription';

// temporary hack until https://github.com/ng-bootstrap/ng-bootstrap/pull/1602 is merged

@Directive({
  selector: '[ngbPopover]' // tslint:disable-line
})
export class PopoverDirective implements OnDestroy, AfterViewChecked {
  @Input() popoverClass: string;

  private shownSubscription: Subscription;

  private hiddenSubscription: Subscription;

  private popoverWindowElm: ElementRef;

  constructor(private renderer: Renderer2, popover: NgbPopover) {
    this.shownSubscription = popover.shown.subscribe(() => {
      this.popoverWindowElm = popover['_windowRef'].location;
    });
    this.hiddenSubscription = popover.hidden.subscribe(() => {
      this.popoverWindowElm = null;
    });
  }

  ngAfterViewChecked(): void {
    if (this.popoverWindowElm) {
      this.renderer.addClass(
        this.popoverWindowElm.nativeElement,
        this.popoverClass
      );
    }
  }

  ngOnDestroy() {
    this.shownSubscription.unsubscribe();
    this.hiddenSubscription.unsubscribe();
  }
}

```

**Comment by chelaruc** [comment]
Hi, @mattlewis92 ! When can we use this feature? I need it for my projects.

**Comment by shyamal890** [comment]
@chelaruc Actually the right person to ask as to why this PR is not merged is @pkozlowski-opensource I guess. 

Btw, this is 'a must' feature.

**Comment by shyamal890** [comment]
@mattlewis92 should I added the `directive` to the main `AppModule's` declarations?

**Comment by pkozlowski-opensource** [comment]
We are going to merge #2310 instead as:
* this one doesn't merge cleanly any more
* #2310 has demo

**Pull request closed without merging**
