### PR TITLE
fix: restore full AoT compatibility

### LINKED ISSUE #796: ng-bootstrap causes AOT to fail with module not found errors.
### Bug description:
When I import @ng-bootstrap and run AOT, I get the following errors and more

```
ERROR in ./src/app/app.module.ngfactory.ts                                                                    
Module not found: Error: Can't resolve '../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory' i
n '/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/src/app'                                        
 @ ./src/app/app.module.ngfactory.ts 84:15-93                                                                 
 @ ./src/main.browser.aot.ts                                                                                  
                                                                                                              
ERROR in ./src/app/app.module.ngfactory.ts                                                                    
Module not found: Error: Can't resolve '../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ng
factory' in '/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/src/app'                              
 @ ./src/app/app.module.ngfactory.ts 85:15-103                                                                
 @ ./src/main.browser.aot.ts                                                                                  
                                                                                                              
ERROR in ./src/app/app.module.ngfactory.ts                                                                    
Module not found: Error: Can't resolve '../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactor
y' in '/Users/qdouble/Sites/EXAMPLE_APPS/angular2webpack2-starter/src/app'                                    
 @ ./src/app/app.module.ngfactory.ts 88:15-97                                                                 
 @ ./src/main.browser.aot.ts    
```

When I check the compiled files, it appears that many components are not being generated. 

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.0.1

ng-bootstrap: 1.0.0-alpha.6

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #796

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
The fix for AoT from this PR boils down to 2 things:
* removal of the `@internal` annotation in our docs - this annotation is processed by TS and when encountered typings are not generated for the annotated thing.
* exporting directives from module files - this is a work-around for https://github.com/angular/angular/issues/11889

**Comment by smith64fx** [comment]
Awesome! Gonna try this later.

**Comment by alanpurple** [comment]
Is AoT compile available for alpha.6? or is it up to alpha.7?

**Comment by tinchou** [comment]
Awesome! I'm waiting impatiently to try this out :). I tried to install directly from GitHub but I get this error:

```
node misc/validate-commit.install.js
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '.............\node_modules\ng-bootstrap\.git\hooks\commit-msg'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.<anonymous> (.......................\node_modules\ng-bootstrap\misc\validate-commit.install.js:10:6)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
npm WARN install:ng-bootstrap@1.0.0-alpha.6 ng-bootstrap@1.0.0-alpha.6 install: `node misc/validate-commit.install.js`
npm WARN install:ng-bootstrap@1.0.0-alpha.6 Exit status 1
```

Any ideas?

I can confirm by inspecting the diffs that you fixed all of my errors with the changes here and [here](https://github.com/ng-bootstrap/ng-bootstrap/commit/5c5361cf85ece60e2c14d78e53630734da7e682a), but I'm not able to test it.

Maybe if you published an alpha 7 it would be easier :).

Thanks!

**Comment by pkozlowski-opensource** [comment]
alpha.7 with aot compatibility will be cut alter today.

**Comment by tinchou** [comment]
You rock dude!

**Comment by pkozlowski-opensource** [comment]
For anyone tracking AoT compatibility - I've just pushed alpha.7 to npm so you can download it and take for the test drive. Be sure to check the [breaking changes section](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#breaking-changes) while updating! The demo site updated to alpha.7 should be up shortly.

**Pull request closed without merging**
