### PR TITLE
fix(popover): fix positioning after the beta2

### PR DESCRIPTION
**Pull request by fbasso**

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Comment by fbasso** [comment]
Thanks @maxokorokov :)

**Comment by maxokorokov** [comment]
@fbasso haha, that wasn't me, you know ;)

**Comment by fbasso** [comment]
Ah yes, read too quickly, but it doesn't matter as the code is good 😄

By the way, thanks @peterblazejewicz for your code review !

**Pull request merged**
