### PR TITLE
feat(modal): Add vertically centered option

### LINKED ISSUE #1124: center modal vertically option
Add new configuration option to the open api to make the modal vertically centered
please check UIKIT framework style of doing this
https://getuikit.com/docs/modal.html

I'm suggesting to add an option called "center" type boolean, if it's set to true to vertically center the modal in the page

thanks!

### PR DESCRIPTION
**Pull request by bastienmoulia**
Fix #1124

Also rename the modal documentation **custom class** in **options** with the following options:
- windowClass: 'dark-modal'
- size: 'sm'
- size: 'lg'
- verticallyCentered: true

### CODE REVIEW

**Comment by thiagog3** [comment]
I really need this!

**Comment by travis1234** [comment]
I would be happy to test this in my project. 
Is there an easy way to import this version/commit using npm?

**Comment by DamianKedzior** [comment]
+1 For vertically centered option which is build-in in Bootstrap: https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered
It just requires adding a new class. I tried to achieve it by adding "modal-dialog-centered" class to "windowClass" option but it adds the class to <ngb-modal-window> element instead of first <div> element which has "modal-dialog" class applied.

Maybe "windowClass" should add these classes directly to <div class="modal-dialog"> element instead of <ngb-modal-window> element.

**Comment by thylux** [comment]
Looking forward to use this too.

**Comment by wgraham17** [comment]
Any chance this can get reviewed and pulled in?

**Comment by pkozlowski-opensource** [comment]
Adding it to the next feature-release (1.1.0) milestone.

**Comment by pkozlowski-opensource** [comment]
Thnx so much for this PR @bastienmoulia - I've resolved conflicts and landed it as 00e79c4 .
I've also changed the option name to better align with the Bootstrap's class name

**Pull request closed without merging**
