### PR TITLE
demo: add solarized light

### LINKED ISSUE #414: Code in black background in demo is hard to read
I have, like almost 10% of the male population, a (light) color vision deficiency.
This makes it quite hard for me to read the code in the demos, mainly because their background is black (the purple or pink or whatever color used for html elements, in particular, is hard for me to read).

I know JavaScript hipsters like their dark background :-) But in my experience, I and other people I know who have color vision deficiencies have much less problem reading code when it's more traditionally written in black or dark colors, on a white background.

Would you consider changing the color theme of the code, or providing a simple way to switch to a more traditional color theme?

### PR DESCRIPTION
**Pull request by Foxandxss**
This changes the demo themes from the dark one to solarized light.

Also moved the vendor CSS to the vendor bundle. Not really important for our demo but I like to keep the things clean.

Fixes #414

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Just pulled and tried this out. IMO it looks better than the dark theme so it goes in the right direction. I was just wondering if a more greyish background wouldn't be better. The yellowish color somehow stands out for me as not really in-line with other collors on our demo site.

Will check other prism themes just to see.

**Comment by Foxandxss** [comment]
There isn't too many choices. I am not thaaat fond of it either, but is better.

**Comment by pkozlowski-opensource** [comment]
Just checked all the available in the default prism package and the only one I like is `coy`. It looks really nice on our demo site but has those slightly annoying stripes.

**Comment by Foxandxss** [comment]
Could be removed perhaps with custom CSS on top.

**Comment by mendeza** [comment]
@jnizet is your "affected user representative" in this case, and he stated a preference for the default theme in #414.

**Comment by pkozlowski-opensource** [comment]
Yeh, default one looks a bit nicer on our page. We could further change it to have a bit more greyish background.

**Comment by jnizet** [comment]
Regarding the readability issue, both solarized and default fix the issue for me.

My preference would go for the default theme, with a background color identical to the one of the card header. But that's only my preference.

**Comment by Foxandxss** [comment]
@jnizet Feel free to create a PR with some custom idea and we will see.

**Comment by jnizet** [comment]
@Foxandxss I just did. See #417

**Pull request closed without merging**
