### PR TITLE
feat(modal): Add option to drag the modal

### LINKED ISSUE #1378: How to make the modal can be dragged.
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:2.4

ng-bootstrap:

Bootstrap:

i want to know ...thanks

### PR DESCRIPTION
**Pull request by bastienmoulia**
Add an option `draggableSelector`.
By example, with the option `{ draggableSelector: '.modal-header' }` the header of the modal can be draggable.
Fix #1378

### CODE REVIEW

**Comment by maxokorokov** [comment]
A quick scan telling me that overall tests are missing.
Also maybe we should find a way to isolate and test the logic in `dragModal`, have a service for it or something?

**Comment by pkozlowski-opensource** [comment]
> Also maybe we should find a way to isolate and test the logic in dragModal, have a service for it or something?

Agree with @maxokorokov - this should be something independent of the core modal functionality. Ideally I would see it as an extension living outside of `ng-bootstrap`, ideally in the user-land...

**Comment by shyamal890** [comment]
This would be a great addition to `ng-bootstrap`

**Comment by LastCodeDE** [comment]
We need this feature, too. We are using a lot of modal views but they are not draggable.

**Comment by LastCodeDE** [comment]
We need this feature, too. We are using a lot of modal views but they are not draggable.

**Comment by LastCodeDE** [comment]
We need this feature, too. We are using a lot of modal views but they are not draggable.

**Comment by pkozlowski-opensource** [comment]
Thnx for the PR @bastienmoulia but we will pass on it for now. Bootstrap itself is not providing this functionality and we consider that it adds very little to the user's experience. On the other hand it would penalise other people using this library with additional code etc.

We could merge a PR that would introduce this functionality in a separate directive that would be tree-shakable, though.

**Comment by deeg** [comment]
I am also looking for similar functionality, and might consider doing as requested @pkozlowski-opensource.

Just checking, is this something you would still consider accepting as a PR as long as it followed your state guidelines?

> We could merge a PR that would introduce this functionality in a separate directive that would be tree-shakable, though.

**Pull request closed without merging**
