### PR TITLE
fix: replace the division by math.div for sass

### PR DESCRIPTION
**Pull request by fbasso**
The division is now deprecated with sass-dart, and must be replaced by math.div

### CODE REVIEW

**Comment by maxokorokov** [comment]
It is failing, isn't it?
Screenshot 2021-07-01 at 11 17 53

**Comment by fbasso** [comment]
> It is failing, isn't it?

Hum... Strange, I haven't seen that locally. It's probably the same thing of the warning displayed only once after the first build, even after several consecutive builds.

I'll check it.

**Review by lionel-meunier — APPROVED** [review]

**Comment by lionel-meunier** [comment]
the sass@1.32.12 package is installed while the ^1.33.0 package is needed

need update angular to ^12.1

**Comment by fbasso** [comment]
Thanks @lionel-meunier ! I'll try it.

**Comment by maxokorokov** [comment]
not relevant anymore, closing

**Pull request closed without merging**
