### PR TITLE
chore: don't preserve licence comments in demo bundles

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Without this option we are including licence info from each and every file.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Build is failing due to https://github.com/floridoo/gulp-sourcemaps/issues/238 ....

Time for shrinkwrap / Yarn?

**Comment by phated** [comment]
I'd suggest just pinning package.json to use 1.6 until gulp 4 is released.  We are dropping it from our dependency tree and using something we control instead.

**Comment by pkozlowski-opensource** [comment]
I'd suggest just pinning package.json to use 1.6 until gulp 4 is released. 

Yeh, the breakage was non-obvious since we are not using gulp-sourcemaps. It came as a dependency of `vinyl-fs`:

> ├─┬ gulp-gh-pages@0.5.4
│ ├── gift@0.6.1
│ ├─┬ readable-stream@2.1.5
│ │ ├── buffer-shims@1.0.0
│ │ ├── core-util-is@1.0.2
│ │ ├── isarray@1.0.0
│ │ ├── process-nextick-args@1.0.7
│ │ ├── string_decoder@0.10.31
│ │ └── util-deprecate@1.0.2
│ ├─┬ vinyl-fs@2.4.3
│ │ ├─┬ duplexify@3.4.5
│ │ │ ├─┬ end-of-stream@1.0.0
│ │ │ │ └── once@1.3.3
│ │ │ ├─┬ readable-stream@2.1.5
│ │ │ │ └── isarray@1.0.0
│ │ │ └── stream-shift@1.0.0
│ │ ├─┬ glob-stream@5.3.5
│ │ │ ├── glob@5.0.15
│ │ │ ├─┬ glob-parent@3.0.0
│ │ │ │ └─┬ is-glob@3.1.0
│ │ │ │   └── is-extglob@2.1.0
│ │ │ ├─┬ ordered-read-streams@0.3.0
│ │ │ │ └── is-stream@1.1.0
│ │ │ ├─┬ through2@0.6.5
│ │ │ │ └─┬ readable-stream@1.0.34
│ │ │ │   └── isarray@0.0.1
│ │ │ ├─┬ to-absolute-glob@0.1.1
│ │ │ │ └── extend-shallow@2.0.1
│ │ │ └─┬ unique-stream@2.2.1
│ │ │   └─┬ json-stable-stringify@1.0.1
│ │ │     └── jsonify@0.0.0
│ │ ├─┬ gulp-sourcemaps@1.7.3

Good to her @phated that you are taking control / dropping this dependency, it is kind of crucial part of the gulp ecosystem.

**Comment by phated** [comment]
We've pinned it in the interim, too.

**Pull request closed without merging**
