### PR TITLE
feat: bump up Angular dependency to 4.0.3

### LINKED ISSUE #1337: template has been deprecated, need to change over to ng-template
I took a peek at Angular 4.0.0-rc.1, and noticed messages that the `template` tag has been deprecated in favor of `ng-template` - this is a breaking change that will need to be scheduled sometime after Angular 4 goes live.

### LINKED ISSUE #1433: Problems using accordion inside accordion with Angular 4
I need to use an accordion with other accordions inside. When i was using Angular 2, i worked perfect but when i update to angular 4 using angular-cli 1.0, It stops working.

Here is the code:

```

<ngb-accordion>
    <ngb-panel title="First panel">
        <template ngbPanelContent>
            <ngb-accordion>
                <ngb-panel id="1" title="First panel">
                    <template ngbPanelContent>
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
                        on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
                        raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </template>
                </ngb-panel>
            </ngb-accordion>
        </template>
    </ngb-panel>
</ngb-accordion>

```

### LINKED ISSUE #1439: Move to Angular 4
There are several things that need to happen in order to fully move to Angular 4 (note: we do support Angular 4 already, this issue just summarizes things that need to happen to fully drop support to Angular 2):
* [x] cut a bug fix release just before (so people still on Angular 2.x can update)
* [x] change all the references from `<template>` to `<ng-template>` in src code
* [x] change all the references from `<template>` to `<ng-template>` in docs
* [x] update generated package.json constraints
* [x] update versions in documentation (demo, README etc.)
* [x] update plunker templates to use just one variable for ng versions (instead a separate one for core and a different one for a router)
* [x] add breaking change section to the release commit

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Closes #1337
Closes #1415
Closes #1433
Closes #1439

BREAKING CHANGE:

ng-bootstrap requires a minimal version of Angular 4.0.3

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Let's wait a day or two to see if people don't report problems with the freshly released 1.0.0-alpha.24  and if not - let's get this one in!

**Comment by Danteisabck** [comment]
Hello, i update ng-bootstrap to 1.0.0-alpha.24, but in build aot i have a same problem 
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  <div class="card">
    [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
      <div role="tab" id="{{panel.id}}-header"
        "): ng:///D:/widget/web-widget/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4

**Comment by pkozlowski-opensource** [comment]
@Danteisabck of course, since this PR wasn't merged / released yet.... IT will be part of alpha.25. For now you can safely ignore the warning.

**Comment by Danteisabck** [comment]
@pkozlowski-opensource 1. can your tell when you are planning to merge this PR ? 
2. And i have a silly question, if I use build aot i get this warnings but if i use build jit i don't get these warnings, i try to use carousel, can it be a problem with tsconfig aot ?

**Pull request closed without merging**
