### PR TITLE
docs: add a note about style needed for scroll to work

### LINKED ISSUE #4571: Offcanvas opened via Component - Body doesn't scroll
### Bug description:

When opening an offcanvas drawer with a body that overflows, the scrollbar never appears. The images below were created on the demo site. Note: This only occurs when using a component, likely due to the extra node. 

image
image

### Link to minimally-working StackBlitz that reproduces the issue:

I took your example, changed what we pass in to induce a scroll. 
[https://stackblitz.com/edit/angular-rdhvry?file=src%2Fapp%2Foffcanvas-component.ts](https://stackblitz.com/edit/angular-rdhvry?file=src%2Fapp%2Foffcanvas-component.ts)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 16.2.7

ng-bootstrap: 15.1.1

Bootstrap: 5.3.1

### PR DESCRIPTION
**Pull request by majora2007**
This updates the demo of offcanvas with component to indicate the need for a host style for scrolling within the offcanvas to work. 

Closes #4571

### CODE REVIEW

**Comment by majora2007** [comment]
@jnizet Any chance for a review and merge? Please let me know if you would like something more explicit on the documentation.

**Comment by jnizet** [comment]
@majora2007 LGTM, but it would be nice if you could add a note in the textual description of the demo. Something like:
> Note that when using a component as content, the additional node introduced in the markupo requires the component to have additional CSS styles to be applied if you want the content to be scrollable. See the code sample for details.

**Comment by majora2007** [comment]
All done, ready for a review again.

**Comment by jnizet** [comment]
LGTM. I'll let @maxokorokov merge if it's OK with him.

**Pull request merged**
