### PR TITLE
chore: use angular 5.0.0

### PR DESCRIPTION
**Pull request by bastienmoulia**
With the update to angular 5.0.0, other dependencies are updated:
```
@ngtools/webpack: 1.3.0 => 1.8.0
rxjs: ^5.0.1 => ^5.5.2
ts-loader: 2.0.0 => 3.1.1
typescript: 2.1.5 => 2.4.2
```
And I have to change `AotPlugin` by `AngularCompilerPlugin` following https://www.npmjs.com/package/@ngtools/webpack#usage

ng-bootstrap/ng-bootstrap#1938
ng-bootstrap/ng-bootstrap#1778

### CODE REVIEW

**Comment by bastienmoulia** [comment]
TODO : Change `new AngularCompilerPlugin()` by `new ngToolsWebpack.AngularCompilerPlugin()`

https://github.com/angular/angular-cli/blob/2b982d2cba401b843579447063d20f0dd053b973/tests/e2e/assets/webpack/test-app-ng5/webpack.config.js

**Comment by bastienmoulia** [comment]
Is that a memory error with Travis? Is it possible to relaunch the test?

**Comment by klozano** [comment]
any news on this?

**Comment by yazshel** [comment]
`yarn test` passes fine on my system for this PR. As ng-bootstrap is the only thing holding my project back from upgrading to Angular 5, so I for one would love to see this PR merged ASAP. So please relaunch the TravisCI tests...

**Comment by guillaume-ro-fr** [comment]
Hi @bastienmoulia 

You need to close and reopen this PR to relaunch the Travis test according to this comment (https://github.com/travis-ci/travis-ci/issues/576#issuecomment-65317915) 😉

**Comment by bastienmoulia** [comment]
@guillaume-ro-fr thanks I will do that !

**Comment by bastienmoulia** [comment]
Error linked to https://github.com/angular/angular-cli/issues/5618

**Comment by bastienmoulia** [comment]
To recap, there are memory issues on the latest versions of the AOT compiler of angular, so I update to the latest versions of [webpack](https://github.com/webpack/webpack) and [@ngtools/webpack](https://github.com/angular/angular-cli) for it to work well.

It is also advisable to use Node 8 LTS to further reduce memory but I have not made this change.

**Comment by pkozlowski-opensource** [comment]
Thnx so much for this PR @bastienmoulia - much appreciated. Merged to master, will be released today.

**Pull request closed without merging**
