### PR TITLE
feat(carousel): add animation

### PR DESCRIPTION
**Pull request by linusbrolin**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

This adds animations to the carousel.
I have tried to make them work as close to the official Bootstrap animations as I could, except using Angular animations instead of Bootstraps css animations.

This is my first PR to ng-bootstrap, but I have tried to follow all the conventions.
Let me know if there is something I have missed or done wrong.

### CODE REVIEW

**Comment by linusbrolin** [comment]
As far as I can tell, the only Travis error I get is completely unrelated to my code:

> IE 11.0.0 (Windows 8.1 0.0.0) ngb-datepicker ngModel should switch month on prev/next navigation click FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

I haven't touched ngb-datepicker.

**Comment by dgutride** [comment]
We'd love to see this enhancement as well - any update on the potential for merging this?

**Comment by mboughaba** [comment]
Indeed it would be nice to have the ng carousel animated the way bootstrap carousel does.

**Comment by linusbrolin** [comment]
Apparently there are limitations with Angulars animation system that they want to fix before implementing any animations. :/
See this comment: https://github.com/ng-bootstrap/ng-bootstrap/issues/295#issuecomment-382014741

**Comment by bostondevin** [comment]
ngx-slick looks pretty promising

**Comment by EliseoPlunker** [comment]
[in this SO](https://stackoverflow.com/questions/57131765/customise-ng-bootrap-carousel-in-angular/57134727#57134727), I write a way to animate ng-carousel using Angular Animation. The update 2 it's about move to left/rigth

**Comment by foo-baar** [comment]
> PR is 5 months old and no movement?
> 
> I'm anxiously awaiting this PR to get merged, how does a carousel in 2017 make it to production without animations? We're about to abandon ng-bootstrap and go with slick.js because our carousels look like they belong on geocities circa 1995.

Wondering, was it finally implemented? I do not see any working examples.

**Comment by maxokorokov** [comment]
Closed, see #3747

**Pull request closed without merging**
