### PR TITLE
feat(tabset): bind tabs to routes

### PR DESCRIPTION
**Pull request by divdavem**
This PR is a suggestion to solve the issue raised in #1632. It allows to easily bind tabs to routes by taking into account the `routerLink` directives on `<ngb-tab>` elements.

For this to work, the new `NgbTabsetRoutingModule` module has to be included in the application and the `routerControlled` attribute has to be defined on the `<ngb-tabset>` element.

Also, the corresponding routes have to be defined in the configuration of the router.
The content of the tabs can be defined either in the corresponding `<ng-template ngbTabContent>` elements, or as the `component` property defined in the router configuration (if the  `<router-outlet>` element is included in the page).

Here is an example:
```html
<ngb-tabset routerControlled>
  <ngb-tab title="First" routerLink="firstTab">
    <ng-template ngbTabContent>
      First content
    </ng-template>
  </ngb-tab>
  <ngb-tab title="Second" routerLink="secondTab">
    <ng-template ngbTabContent>
      Second content
    </ng-template>
  </ngb-tab>
  <ngb-tab routerLink="thirdTab">
    <ng-template ngbTabTitle>Third</ng-template>
    <ng-template ngbTabContent>
      Third content
    </ng-template>
  </ngb-tab>
</ngb-tabset>
```

Note that `NgbTabsetRoutingModule` is a separate module in a different entry point (`"@ng-bootstrap/ng-bootstrap/tabset/routing"`) because it depends on `@angular/router` (and the main entry point does not have this dependency).

Note that this PR also adds an `href` input on `<ngb-tab>` elements, which can be used when `routerControlled` is not set on `<ngb-tabset>` in order to set the `href` used on the tab title anchor.

---

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by divdavem** [comment]
@benouat Thank you for your comment.

Currently, it is not easy to both have the convenient markup offered by &lt;ngb-tabset&gt; and the binding to the router. That's why feature request #1632 was opened. I have opened this PR to suggest a solution. If you have a better idea on how to do it, feel free to share it.

As you are talking about the demo website, the routable tabs there ("Overview", "Example" and "Api") are currently done without the &lt;ngb-tabset&gt; directive at all, so the full bootstrap tab markup is written manually. I find the markup I suggest in this PR much simpler. I have implemented this as an independent module (which is not fake, by the way!) so that there is no negative impact for people who prefer not using it.

**Comment by benouat** [comment]
@divdavem don't get me wrong here, I started a discussion, but I am mostly fine with the changes behind this PR. To me 'fake' just meant that you have to deal with another 'embedded' module as compared to a 'real' one that would come from npm.

So to me, ideally it should be shipped as a standalone module and we still don't know how to do that. How to maintain? how to publish simply several modules? (I am talking about several repos vs. mono-repo, independent lifecycle vs. synchronised version number)

Then it's true that current demo site does not involve the widget now, it used to be the case, and was not that complex to setup. I think people opened #1632 because they simply did not know how to do it. If we document this how to properly with code snippets to copy/paste, then I think we don't need this PR.

Maybe I am wrong, maybe I am totally biased due to my experience, especially with demo website.

**Comment by divdavem** [comment]
@benouat Thank you for your answer.

I don't think people opened #1632 only because they did not know how to do it, but also because the `<ngb-tabset>` component itself makes it more complex to do it than when using the raw markup from bootstrap, because it wraps `<a>` elements, so it is no longer possible to put `routerLink` directives on them. So, with `<ngb-tabset>`, it is not possible anymore to link tabs with the router in a declarative way, some javascript/typescript code is required too. With this PR, I am trying to restore the ability to do it only with markup, so I think it makes sense to share the code and avoid having people re-write that JS/TS code each time they need to bind tabs to the Angular router.

**Comment by asvishnyakov** [comment]
This feature is not about markup, You need it if you use server side rendering and want good SEO

**Comment by maxokorokov** [comment]
Closing this in favour of #1584, where you can use navs with router links directly

**Pull request closed without merging**
