### PR TITLE
Provide more specific instructions for css

### PR DESCRIPTION
**Pull request by huntc**
Fixes https://github.com/ng-bootstrap/ng-bootstrap/issues/2203

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [] built and tested the changes locally.
 - [] added/updated any applicable tests.
 - [] added/updated any applicable API documentation.
 - [] added/updated any applicable demos.

### CODE REVIEW

**Comment by huntc** [comment]
Flaky test for CI? All that I changed was the doc...

**Comment by bastienmoulia** [comment]
Bootstrap should not be install with `npm install bootstrap` as it is already install with ng-bootstrap.

And for the import it's better to use the ~ instead of a relative path:
``` css
@import "~bootstrap/dist/css/bootstrap.css"
```

And maybe add an exemple of scss import:
``` scss
@import "~bootstrap/scss/bootstrap"
```

**Comment by pkozlowski-opensource** [comment]
@huntc thnx for taking time to send this PR. I totally agree that we need a better installation instructions but IMO your proposal assumes too many things (ex. what is `styles.css`? what if I want to use SASS?). Your description might be fine for some users but confusing for others...

What we are going to do is to add more detailed instructions for the CLI users. It is even better as we will be able to provide a ng-bootstrap schematics so make the whole installation instruction even easier! 

Closing based on the above.

**Comment by Bridgeway** [comment]
Logically, command line interfaces are actually deprecated technology, with the advent of a WIMP environment as an upgrade to ms-dos all those years ago, why not just make everything visual ??

**Comment by moniuch** [comment]
@pkozlowski-opensource [I was just about to submit a similar PR] Why was this PR by @huntc closed? (as I understand - without merging). While I understand that the project wants perfect, generic and up-to-date documentation, addressing cli users, this still hasn't happened over past half a year. So why not go the agile way - allow users to contribute, save others from wasting time googling for basic info, and  improve the docs successively?

**Comment by itsnamgyu** [comment]
Is there any follow-up issue on this? The installation guide in `README.md` has been fixed in 97ed39f including more verbal instructions on this issue, while the [getting-started guide](https://ng-bootstrap.github.io/#/getting-started) does not seem to be updated accordingly.

**Comment by Yiidiir** [comment]
@bastienmoulia `bootstrap` wasn't automatically installed when i installed `ng-bootstrap` !
Maybe a ce=leaner way to do this is:
in angular.json
```
            "styles": [
              "src/styles.css",
              "./node_modules/bootstrap/dist/css/bootstrap.css"
            ],
```

**Pull request closed without merging**
