### PR TITLE
1 1 maintanance

### PR DESCRIPTION
**Pull request by atkinsl88**
Before submitting a pull request, please make sure you have at least performed the following:

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated any applicable tests.
 - [ ] added/updated any applicable API documentation.
 - [ ] added/updated any applicable demos.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@atkinsl88 It looks like you've pushed some outdated bits? Is that expected?

**Comment by benouat** [comment]
@atkinsl88 would you mind describing what you're trying to achieve here ?

**Comment by atkinsl88** [comment]
Sorry, it was a mistake. I was following a tutorial, I'm really sorry if I have broken something.

**Comment by benouat** [comment]
Thanks for the update!
I'll then close the PR

**Pull request closed without merging**
