### PR TITLE
chore(demo): new version of website

### PR DESCRIPTION
**Pull request by benouat**
Regarding discussion that started in #2350 I came up with a redesign of the homepage, which is as the previous versions, heavily inspired from Bootstrap itself.

Then with this new homepage, I got motivated to actually perform an entire re-design of the website.

This is what this PR is about.

Instead of forcing you to clone and setup up locally to have a look, I have pushed the aot build on https://benouat.github.io/ng-bootstrap-2018/

Feel free to comment. And please do try to play with responsive aspect of it. Don't hesitate to resize a lot the window, especially on component pages, as I tried to make it really dynamic.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Love it @benouat !

Just 2 nits:
* the 6 icons at the bottom of the page look kind of small as compared to other pieces on the page;
* not sure about the button to switch between examples / API on a component's page - maybe it is just about a color?

**Comment by benouat** [comment]
> the 6 icons at the bottom of the page look kind of small as compared to other pieces on the page

We could try to make icons bigger when in desktop/wide screen mode, keeping them as it is here for tablet/mobile

> not sure about the button to switch between examples / API on a component's page - maybe it is just about a color?

For the button, I admit that the color here might be disturbing. First of all, I clearly wanted in the first place to get rid of the annoying tabbar I introduced myself one year ago. I did not like it back then, and it did not change, I can't stand it anymore. 😄 

So my idea was to stick with standard BS buttons. I tried several BS colors... none of them is better that each other. The one I picked sounded to be the less weird.

**Comment by benouat** [comment]
Some tests here

image

image

I like it better 👍

**Comment by pkozlowski-opensource** [comment]
I'm going to merge this since I believe that this is a wast improvement over the existing demo site. We can always iterate on improvements. Thnx @benouat !

**Pull request closed without merging**
