### PR TITLE
Merge fix(tabset): remove aria-expanded and use aria-selected instead…

### PR DESCRIPTION
**Pull request by constantincechina**
… (#3292) from 5.1.0 to 4.2.x

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

This is a fix ported from version 5.1.0

### CODE REVIEW

**Comment by constantincechina** [comment]
@fbasso Can you please take a look at the current PR? Thanks

**Comment by constantincechina** [comment]
@benouat  Can you please take a look at the current PR? Thanks

**Comment by constantincechina** [comment]
@maxokorokov Can you please take a look at the current PR? 
This issue has been fixed in latest version(5.x) - that make use of Angular > 8.x. However for the projects that are using version 7 of Angular - this fix is not available.

Is the development and support no longer available for the version 4 - and if so, where info is available/published?
Thanks

**Comment by constantincechina** [comment]
Good evening @benouat and thanks for the reply! vacation in August - looks like you are working for Government agency :D.

I'll check the things you mentioned - however - I recall that simply trying just to merge the fix, did not work and was failing the Travis CI.
The changes added to `package.json`  were required to fix the protractor version issue for the Chrome headless browser that was not able to identify the correct version.

In regards to the  `code-highlight.service.ts` that was due to the upgrade version for @angular-devkit/build-angular. I'll try to revert these and post the update here.

**Comment by maxokorokov** [comment]
@constantincechina thanks for the PR, but it was much easier for me to cherry-pick the commit and do a release from there. It's a part or 4.2.2 now.

**Pull request closed without merging**
