### PR TITLE
feat(modal): Add xl size for modal

### PR DESCRIPTION
**Pull request by bastienmoulia**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

Add the extra large (xl) modal size, available with Bootstrap 4.2.
https://getbootstrap.com/docs/4.2/components/modal/#optional-sizes

### CODE REVIEW

**Comment by changhuixu** [comment]
The documentation has not updated yet.
The `modal-config.d.ts` has not updated to reflect usage of "xl".
But, the modal dialog is in XL size, if I ignore the ts lint error with 'xl'. 

Can anyone update this merge?

**Comment by IAfanasov** [comment]
tried to take care of this PR. Looks like there is no bootstrap class for the extra large modal. is it acceptable to create our classes for stuff we miss in bootstrap or credo of this project is to follow bootstrap and port it without adding new functionality?

**Comment by changhuixu** [comment]
Hi @IAfanasov ,

`.modal-xl` is a valid bootstrap class.

--



> tried to take care of this PR. Looks like there is no bootstrap class for the extra large modal. is it acceptable to create our classes for stuff we miss in bootstrap or credo of this project is to follow bootstrap and port it without adding new functionality?
> 
> Changes I made: [IAfanasov@3fa27e2](https://github.com/IAfanasov/ng-bootstrap/commit/3fa27e24b38dc70c6e83c8fbcc8d2003dedddb8b)

**Comment by IAfanasov** [comment]
> `.modal-xl` is a valid bootstrap class.

thanks @changhuixu ! found it in bootstrap sources. Now figuring out why I don't see styles for this class while testing extra large modal

**Comment by benouat** [comment]
@bastienmoulia would you mind rebasing this PR ? There are some conflicts.

**Comment by IAfanasovMob** [comment]
> @bastienmoulia would you mind rebasing this PR ? There are some conflicts.

this one needs bootstrap 4.2 or higher. suppose it makes sense to get back to it after ng-bootstrap 5 released.

**Comment by benouat** [comment]
@IAfanasov yes I know, I am preparing the work here. `5.0.0-rc.0` is round the corner :)

Bootstrap will be bumped to `4.3.1` with #3220. We always update deps outside of PR's (hence @maxokorokov [comment](https://github.com/ng-bootstrap/ng-bootstrap/pull/2943#pullrequestreview-190667992) to revert changes to both `package.json` and lock file)

Thus, a single rebase should be needed, done before or after #3220 lands does not matter.

**Comment by IAfanasov** [comment]
> @bastienmoulia would you mind rebasing this PR ? There are some conflicts.

rebased version https://github.com/ng-bootstrap/ng-bootstrap/pull/3239
I don't mind to wait for @bastienmoulia to rebase this pr

**Comment by benouat** [comment]
@bastienmoulia sorry for that, but as I did not get any news from you, I'll close that PR in go ahead with #3239 which is rebased and did not touch pakage.json nor yarn.lock

**Pull request closed without merging**
