### PR TITLE
docs: update installation instructions

### PR DESCRIPTION
**Pull request by maxokorokov**
As more people are unclear what to do with CSS, here is another update to installation instructions. Based on  https://github.com/ng-bootstrap/ng-bootstrap/issues/2203#issuecomment-450644888

<details>
  <summary>Click to see the screenshot</summary>

Screen Shot 2020-04-03 at 14 59 47

</details>

But we'd better release updated schematics.

### CODE REVIEW

**Comment by maxokorokov** [comment]
@benouat, thanks, updated

Screen Shot 2020-04-06 at 11 01 46

**Comment by 4javier** [comment]
If you suggest to install bootstrap by npm, your examples should show the import from the correct initial path, that's node_modules, not home.

> /* update your 'styles.css' with */
@import 'node_modules/bootstrap/dist/css/bootstrap.css';
>
>/* or your 'styles.scss' with */
@import "node_modules/bootstrap/scss/bootstrap";

**Comment by benouat** [comment]
It may be confusing, but it’s not referencing an home folder! It’s a SASS convention that points to `node_modules`.

**Comment by 4javier** [comment]
The most unintuitive convention I've seen in a long time...
Anyway, it seems that's a webpack fetaure, not a SASS one.
https://stackoverflow.com/a/37118406/6350583
Actually, I don't use webpack, and if I replace "node_module" with "~" inside my import statement this is what I get

> ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--15-3!./src/styles.scss)
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Can't find stylesheet to import.
>   ╷
> 7 │ @import "~/bootstrap/scss/bootstrap";
>   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   ╵
>   /mnt/dati/workspace/PetMenuAngularFrontend/src/styles.scss 7:9  root stylesheet

**Comment by benouat** [comment]
> It’s a SASS convention.

My bad I was not clear... It's a `sass-loader` convention/feature. `sass-loader` being you're right, a `webpack` plugin, it can only be used via webpack.

Fortunately for us, Angular CLI relies on it under the hood.

It's true, though, that it might be confusing. Although, it is just `~` and not `~/` (that would point to the home directory)

> Actually, I don't use webpack, and if I replace "node_module" with "~"

So I guess in this case, you need to stick to the `node_modules` syntax

**Comment by 4javier** [comment]
Actually I manage my project with npm and ng. Maybe I was using ~/, because now it works.
Thanks for your clarifications.

**Pull request merged**
