### PR TITLE
fix(demo): properly sanitize terms of typeahead

### LINKED ISSUE #1526: Typeahead documentation bug
Hello, I am not sure whether it is bug or intended to be that way for simplicity purposes. When you type something regexp-like (for example "*") in pretty any typeahead component on the https://ng-bootstrap.github.io/#/components/typeahead page, an error is thrown and that specific component stops working. I clearly understand it is not library bug, but it would be nice to have it fixed.

`ERROR SyntaxError: Invalid regular expression: /* /: Nothing to repeat
    at RegExp (<anonymous>)
    at https://ng-bootstrap.github.io/js/main.ef5e642ec89ff0d6908c.js:1:185226
    at Array.filter (native)
    at e.project (https://ng-bootstrap.github.io/js/main.ef5e642ec89ff0d6908c.js:1:185200)
    at e._next (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:259293)
    at e.next (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:254634)
    at e._next (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:391369)
    at e.next (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:254634)
    at e.debouncedNext (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:390111)
    at e.o (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:389198)
    at e._execute (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:402319)
    at e.execute (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:402135)
    at e.flush (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:403150)
    at t.invokeTask (https://ng-bootstrap.github.io/js/polyfills.ef5e642ec89ff0d6908c.js:1:60183)
    at Object.onInvokeTask (https://ng-bootstrap.github.io/js/vendor.ef5e642ec89ff0d6908c.js:1:69527)`

### PR DESCRIPTION
**Pull request by wKoza**
Closes #1526

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@wKoza thnx for the PR. I was just thinking if this is the best approach... Maybe we should just drop `RegExp` altogether and use `.indexOf(...)` instead? IMO there is very little value in usage of `RegExp` here. 

WDYT?

**Comment by wKoza** [comment]
yes, we can @pkozlowski-opensource . Something like this ?
`statesWithFlags.filter(v => v.name.toLowerCase().indexOf(term.toLowerCase())>-1).slice(0, 10));`

**Comment by pkozlowski-opensource** [comment]
@wKoza yeh, this was my thinking. Should be easier to grok for people looking at those examples, maybe?

**Comment by pkozlowski-opensource** [comment]
Merged, thnx!

**Pull request closed without merging**
