### PR TITLE
refactor(alert): add custom class to alert component

### PR DESCRIPTION
**Pull request by ulrichdohou**
Before submitting a pull request, please make sure you have at least performed the following:

 - [] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [] built and tested the changes locally.
 - [] added/updated any applicable tests.
 - [] added/updated any applicable API documentation.
 - [] added/updated any applicable demos.

### CODE REVIEW

**Comment by maxokorokov** [comment]
Hey, @ulrichdohou!

Thanks for the PR, however could you please provide a use case for this?

I think you can achieve exactly the same by doing:

```html
<ngb-alert class="myclass">
```

```css
ngb-alert.myclass > div { ... }
```

**Comment by ulrichdohou** [comment]
Hi @maxokorokov 

I was trying to solve the issue related here on stackoverflow https://stackoverflow.com/questions/51450796/apply-classes-to-sub-elements-of-components/51451075?noredirect=1#comment89915498_51451075

<ngb-alert class="myclass"> this way would add the class to the ngb-alert tag and thats not what I was looking for
But this way ngb-alert.myclass > div { ... } should work. But I think adding that option would be fine.

**Comment by pkozlowski-opensource** [comment]
@ulrichdohou thnx for the PR but I believe that we should do #2544 instead.

**Comment by pkozlowski-opensource** [comment]
@ulrichdohou thnx for the PR but we are going to focus on  #2544 and #2552 instead.

**Pull request closed without merging**
