### PR TITLE
Integration with codecov.io

### PR DESCRIPTION
**Pull request by divdavem**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by benouat** [comment]
👏 nice !!

**Comment by maxokorokov** [comment]
Looks very nice to me! Do we have to setup something (ex. give access to Github, create an account) for this to continue working ?

**Comment by divdavem** [comment]
@maxokorokov No, there is nothing mandatory to setup, it works directly.
According to them, it is also possible to install "Codecov's GitHub Integration to improve application link. Comment posting will be on-behalf-of Codecov not a bot user."

**Comment by divdavem** [comment]
@maxokorokov You're welcome! Thank you for integrating my PR!

**Pull request merged**
