### PR TITLE
Use autoprefixer and SCSS for library build

### PR DESCRIPTION
**Pull request by maxkorz**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated any applicable tests.
 - [ ] added/updated any applicable API documentation.
 - [ ] added/updated any applicable demos.

This change enables autoprefixer and CSS minification

Fixes https://github.com/ng-bootstrap/ng-bootstrap/issues/2701

Comparison on file `/dist/esm2015/datepicker/datepicker-navigation.js`
<details><summary>esm2015 output before</summary>

```ts
NgbDatepickerNavigation.decorators = [
    { type: Component, args: [{
                selector: 'ngb-datepicker-navigation',
                changeDetection: ChangeDetectionStrategy.OnPush,
                styles: [`
    :host {
      display: -ms-flexbox;
      display: flex;
      -ms-flex-align: center;
      align-items: center;
    }
    .ngb-dp-navigation-chevron {
      border-style: solid;
      border-width: 0.2em 0.2em 0 0;
      display: inline-block;
      width: 0.75em;
      height: 0.75em;
      margin-left: 0.25em;
      margin-right: 0.15em;
      transform: rotate(-135deg);
    }
    .right .ngb-dp-navigation-chevron {
      transform: rotate(45deg);
      margin-left: 0.15em;
      margin-right: 0.25em;
    }
    .ngb-dp-arrow {
      display: -ms-flexbox;
      display: flex;
      -ms-flex: 1 1 auto;
      flex: 1 1 auto;
      padding-right: 0;
      padding-left: 0;
      margin: 0;
      width: 2rem;
      height: 2rem;
    }
    .ngb-dp-arrow.right {
      -ms-flex-pack: end;
      justify-content: flex-end;
    }
    .ngb-dp-arrow-btn {
      padding: 0 0.25rem;
      margin: 0 0.5rem;
      border: none;
      background-color: transparent;
      z-index: 1;
    }
    .ngb-dp-arrow-btn:focus {
      outline: auto 1px;
    }
    .ngb-dp-month-name {
      font-size: larger;
      height: 2rem;
      line-height: 2rem;
      text-align: center;
    }
    .ngb-dp-navigation-select {
      display: -ms-flexbox;
      display: flex;
      -ms-flex: 1 1 9rem;
      flex: 1 1 9rem;
    }
  `],
                template: `
    <div class="ngb-dp-arrow">
```

</details>

<details><summary>esm2015 output after</summary>

```ts
NgbDatepickerNavigation.decorators = [
    { type: Component, args: [{
                selector: 'ngb-datepicker-navigation',
                changeDetection: ChangeDetectionStrategy.OnPush,
                styles: [`
   :host {
      display: -ms-flexbox;
      display: flex;
      -ms-flex-align: center;
      align-items: center
    }
    .ngb-dp-navigation-chevron {
      border-style: solid;
      border-width: .2em .2em 0 0;
      display: inline-block;
      width: .75em;
      height: .75em;
      margin-left: .25em;
      margin-right: .15em;
      -webkit-transform: rotate(-135deg);
      transform: rotate(-135deg)
    }
    .right .ngb-dp-navigation-chevron {
      -webkit-transform: rotate(45deg);
      transform: rotate(45deg);
      margin-left: .15em;
      margin-right: .25em
    }
    .ngb-dp-arrow {
      display: -ms-flexbox;
      display: flex;
      -ms-flex: 1 1 auto;
      flex: 1 1 auto;
      padding-right: 0;
      padding-left: 0;
      margin: 0;
      width: 2rem;
      height: 2rem
    }
    .ngb-dp-arrow.right {
      -ms-flex-pack: end;
      justify-content: flex-end
    }
    .ngb-dp-arrow-btn {
      padding: 0 .25rem;
      margin: 0 .5rem;
      border: none;
      background-color: transparent;
      z-index: 1
    }
    .ngb-dp-arrow-btn:focus {
      outline: auto 1px
    }
    .ngb-dp-month-name {
      font-size: larger;
      height: 2rem;
      line-height: 2rem;
      text-align: center
    }
    .ngb-dp-navigation-select {
      display: -ms-flexbox;
      display: flex;
      -ms-flex: 1 1 9rem;
      flex: 1 1 9rem
    }`],
                template: `
    <div class="ngb-dp-arrow">
```

</details>

### CODE REVIEW

**Comment by maxokorokov** [comment]
I formatted the `esm2015 output after` to compare more easily

**Comment by maxkorz** [comment]
@maxokorokov I added the `esm2015 output after` as-is to demonstrate that with SCSS the css output is being minified 😃

**Comment by maxokorokov** [comment]
I think you can see the message edit history, so it should be fine :)

**Comment by maxkorz** [comment]
@maxokorokov done
P.S. Looks like CI doesn't like me.

**Comment by maxokorokov** [comment]
Thanks, relaunched CI!

**Comment by maxokorokov** [comment]
@pkozlowski-opensource, please take a look when you have time and merge if looks ok to you.

2 changes here:
- use autoprefixer for internal component styles (same browserlist as for bootstrap)
- extract inline styles to `scss` files (required for autoprefixer to work)

**Comment by pkozlowski-opensource** [comment]
LGTM

**Pull request merged**
