### PR TITLE
feat(progressbar): add stacked input

### LINKED ISSUE #905: Feature (Progressbar): Stacked Progressbar
Is there support for a stacked progress bar like in ui-bootstrap: https://angular-ui.github.io/bootstrap/#/progressbar?

### PR DESCRIPTION
**Pull request by bastienmoulia**
fix #905

### CODE REVIEW

**Review by maxokorokov — COMMENTED** [review]
Hey @bastienmoulia,

what do you think about this API?


```html
<ngb-progressbar-stack>
  <ngb-progressbar type="danger" [value]="20"></ngb-progressbar>
  <ngb-progressbar type="warning" [value]="50"></ngb-progressbar>
  <ngb-progressbar type="success" [value]="30"></ngb-progressbar>
</ngb-progressbar-stack>
```

It will avoid having `@Input()` completely that you have to repeat. Just optionally inject the stack in the progressbar. If it's there →  we're in the stack, if not → it's a standalone progressbar.

Do you think it would work ?

**Comment by maxokorokov** [comment]
I missed this migration completely oO

Also it might be good to move attributes from the inner `div` → https://getbootstrap.com/docs/5.3/migration/#progress-bars

**Comment by bastienmoulia** [comment]
> Also, if you're working on this, it might be good to move attributes from the inner `div` to match the new markup → https://getbootstrap.com/docs/5.3/migration/#progress-bars

It was already done in https://github.com/ng-bootstrap/ng-bootstrap/pull/4461

**Comment by bastienmoulia** [comment]
> Hey @bastienmoulia,
> 
> what do you think about this API?
> 
> ```
> <ngb-progressbar-stack>
>   <ngb-progressbar type="danger" [value]="20"></ngb-progressbar>
>   <ngb-progressbar type="warning" [value]="50"></ngb-progressbar>
>   <ngb-progressbar type="success" [value]="30"></ngb-progressbar>
> </ngb-progressbar-stack>
> ```
> 
> It will avoid having `@Input()` completely that you have to repeat. Just optionally inject the stack in the progressbar. If it's there → we're in the stack, if not → it's a standalone progressbar.
> 
> Do you think it would work ?

It's working !

**Review by maxokorokov — CHANGES_REQUESTED** [review]
Hey, @bastienmoulia, LGTM!

Just 2 comments:
- you should export it from the `src/index.ts` as well
- I was also thinking whether it should be a directive or not, but probably component is better as `NgbProgressbar` is a component.

My thinking is:
- if you query with `<ngb-progressbar-stacked #s>`, `s` will be either an element (if directive) or component instance (if component)
- it doesn't have any API really, so won't matter much
- `<ngb-progressbar-stacked>` being a directive is confusing
- if we make it a directive with an attribute(`[ngbProgressbarStacked]`, then writing `<div ngbProgressBarStacked><ngb-progressbar></ngb-progressbar></div>` seems strange to me.


I guess it should stay as component in the end, unless you have other thoughts...

**Comment by bastienmoulia** [comment]
In the long term, I think the 2 components should be deprecated for directives. Like what was done for accordion.

**Review by maxokorokov — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
