### PR TITLE
refactor(sortable-demo): HostBinding HostListener

### PR DESCRIPTION
**Pull request by tbadlov**
This pull request address the usages of HostBinding and HostListener recommendation by Angular Style-06-03 https://angular.io/guide/styleguide#style-06-03.

### CODE REVIEW

**Comment by tbadlov** [comment]
CI fails in elements that this PR hasn't modified:

```
IE 11.0.0 (Windows 10.0.0) ngb-datepicker keyboard navigation should move focus with arrow keys FAILED
	Error: Expected <body class>...</body> to be <div tabindex="0" class="ngb-dp-day" role="gridcell" aria-label="Monday, August 8, 2016">...</div>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
	    at <Jasmine>
	   at expectFocusedDate (http://localhost:9876/_karma_webpack_/main.js:9693:9)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10277:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
	Error: Expected false to be truthy 'You must focus day before triggering key events'.
	    at <Jasmine>
	   at triggerKeyDown (http://localhost:9876/_karma_webpack_/main.js:9656:5)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10279:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
	Error: Expected <body class>...</body> to be <div tabindex="0" class="ngb-dp-day" role="gridcell" aria-label="Tuesday, August 9, 2016">...</div>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
	    at <Jasmine>
	   at expectFocusedDate (http://localhost:9876/_karma_webpack_/main.js:9693:9)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10281:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
	Error: Expected false to be truthy 'You must focus day before triggering key events'.
	    at <Jasmine>
	   at triggerKeyDown (http://localhost:9876/_karma_webpack_/main.js:9656:5)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10283:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
	Error: Expected <body class>...</body> to be <div tabindex="0" class="ngb-dp-day" role="gridcell" aria-label="Tuesday, August 2, 2016">...</div>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
	    at <Jasmine>
	   at expectFocusedDate (http://localhost:9876/_karma_webpack_/main.js:9693:9)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10285:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
	Error: Expected false to be truthy 'You must focus day before triggering key events'.
	    at <Jasmine>
	   at triggerKeyDown (http://localhost:9876/_karma_webpack_/main.js:9656:5)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10287:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
	Error: Expected <body class>...</body> to be <div tabindex="0" class="ngb-dp-day" role="gridcell" aria-label="Monday, August 1, 2016">...</div>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
	    at <Jasmine>
	   at expectFocusedDate (http://localhost:9876/_karma_webpack_/main.js:9693:9)
	   at Anonymous function (http://localhost:9876/_karma_webpack_/main.js:10289:17)
	   at ZoneDelegate.prototype.invoke (http://localhost:9876/_karma_webpack_/vendor.js:97386:17)
```

**Comment by pkozlowski-opensource** [comment]
Honestly, I would preffer that we do _not_ follow the mentioned style-guide here - it is just more verbose for no apparent benefits (or, in other words, benefits are not clear to me).

**Comment by benouat** [comment]
> Honestly, I would preffer that we do _not_ follow the mentioned style-guide here - it is just more verbose for no apparent benefits (or, in other words, benefits are not clear to me).

I would agree with @pkozlowski-opensource here 👍 
The big advantage of using the `host: { }` property in a Component/Directive decorator, is that it is **clear** what the widget is doing.

There might be (unclear) advantages to use _in place_ decorators, but then you are loosing the global overview of listeners for example, which is really bad to me.

Thus, I am afraid we won't merge anytime soon these kind of refactors.

I, nonetheless, would like to thank you @tbadlov to have taken some time opening this PR as your first time contribution. 🏆 🏅

**Comment by tbadlov** [comment]
@benouat  Got it. I wonder why the folks at Angular discourage this implementation then. Thanks for the feedback.

**Pull request closed without merging**
