### PR TITLE
feature(date-picker): added aria-labels to year and month select elem…

### PR DESCRIPTION
**Pull request by RonnBlack**
…ents

Before submitting a pull request, please make sure you have at least performed the following:

 - [] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [] built and tested the changes locally.
 - [] added/updated any applicable tests.
 - [] added/updated any applicable API documentation.
 - [] added/updated any applicable demos.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@RonnBlack based on the discussion in #2543 it doesn't seem like aria labels alone are enough...
Did you tests with screen readers and found different results in your testing?

**Comment by rblack-a3digital** [comment]
Thanks for pointing out the discussion. I hadn't seen this.
I was only basing my changes on recommendations from WAVE (Web Accessibility Evaluation Tool) and I didn't actually test with a screen reader. I'll update the code to add the title property and update the pull request.

**Comment by RonnBlack** [comment]
I added titles to the select elements and tested in Chrome, Firefox, and Edge. I saw now display issues on widows 10 or Mac OS High Sierra (10.13.6). You mentioned that there would be visual impact... do you know of something specific? 

I also tested with Voice Over on Mac and Narrator on Windows and the drop downs seemed to behave as I would expect. It looks like the pull request shows the additional changes I made. If that isn't the case let me know.

**Comment by benouat** [comment]
> You mentioned that there would be visual impact... do you know of something specific?

I think he was mentioning the fact that browsers add a native native _yellow_ tooltip on elements with `title` attribute when you hover them and wait for some milliseconds.

**Comment by RonnBlack** [comment]
Yes the hover behavior is there but the next and previous month buttons also have that behavior. 
In my testing with screen readers it seemed to work fine with just the aria-label even before I added the title. The only problem I noticed is that the Microsoft Narrator didn't announce the label on the Month select but it did properly announce it on the Year. Once title was added it was fine with both. Mac Voice over didn't have a problem either way but IMHO the way it announced what you were on was more confusing (perhaps there is some control over this)

**Pull request merged**
