### PR TITLE
fix(popover): properly destroy popovers using container option

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This is essentially the same as 94a4d5c3d077bdbd41c9ea0b554e24b263b79648

### CODE REVIEW

**Comment by wesleycho** [comment]
LGTM

**Comment by sadlerw** [comment]
@pkozlowski-opensource if the popover is already destroyed this throws an error at https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/popover/popover.ts#L153  This shows up in karma when TestBed.resetTestingModule destroys the view: 
    `TypeError: this._unregisterListenersFn is not a function
	    at NgbPopover.ngOnDestroy (webpack:///~/@ng-bootstrap/ng-bootstrap/popover/popover.js:102:0 <- src/test.ts:63432:14)
	    at Wrapper_NgbPopover.ngOnDestroy (/NgbPopoverModule/NgbPopover/wrapper.ngfactory.js:18:16)`

**Comment by pkozlowski-opensource** [comment]
@sadlerw could you please open a new issue for this with a reproduction scenario in plunker? Thnx!

**Comment by nestorbritez** [comment]
This is because in some cases ngOnDestroy is executing before ngOnInit, I really don't understand why is happening.

Anyways the `_unregisterListenersFn` should be executed in a safe way:

`this._unregisterListenersFn && this._unregisterListenersFn();`

My dirty workaround for now is the next:

```
import { set } from 'lodash-es';
set(NgbPopover.prototype, '_unregisterListenersFn', function() {});
```

**Pull request closed without merging**
