### PR TITLE
feat: upgrade to Angular 11

### LINKED ISSUE #3897: Angular 11 support
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
- Currently able to run v7.0.0 on Angular 11, but consider adding official support

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 11.0.0

ng-bootstrap: 7.0.0

Bootstrap: 4.5.2

### PR DESCRIPTION
**Pull request by santam85**
Ran update schematics and addressed build/testing issues.
Some minor updates to karma reporting were needed in order to work with the latest version.

closes #3897

### CODE REVIEW

**Comment by dezsiszabi** [comment]
I think you can remove the `extractCss` properties from the `angular.json` files to get rid of the following warning during the build:

```
Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
```

Also there's this warning:

```
Warning: Support was requested for IE 10 in the project's browserslist configuration. This browser is no longer officially supported with Angular v11 and higher.
```

Should  `.browserslistrc` files be modified?

`IE 10-11` could become `not IE < 11`
`Explorer >= 10` could become `Explorer >= 11`

**Comment by santam85** [comment]
> I think you can remove the `extractCss` properties from the `angular.json` files to get rid of the following warning during the build:
> 
> ```
> Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
> ```
> 
> Also there's this warning:
> 
> ```
> Warning: Support was requested for IE 10 in the project's browserslist configuration. This browser is no longer officially supported with Angular v11 and higher.
> ```
> 
> Should `.browserslistrc` files be modified?
> 
> `IE 10-11` could become `not IE < 11`
> `Explorer >= 10` could become `Explorer >= 11`

Had to rerun some of the schematics since they didn't trigger due to recoverable syntax errors in code originally.
Added these changes, as well as a few others required by the upgrade of Typescript and other dependencies.

**Comment by santam85** [comment]
@maxokorokov Is there anything blocking review and merge of this PR?

**Comment by maxokorokov** [comment]
@santam85 lack of time, sorry :/
Will merge all the fixes we have for `8.x` and will release `9.0.0` with these changes.

**Comment by rakishii13** [comment]
When are you releasing 9.0.0?

**Review by maxokorokov — APPROVED** [review]
Hey, @santam85!

LGTM, thanks for taking time to do it!

I've cherry-picked your commit and opened a #3941 with couple more fixes on my side:
- Limiting `rxjs` to `^6.5`, not `^6.6` in peer deps (as `@angular/core 11` does for example)
- Adjusting `.browserslstrc` to remove IE mobile and add Edge 18
- dropping IE10 tests

**Pull request closed without merging**
