### PR TITLE
build: replace ngx-build-plus with @angular-builders/custom-webpack

### PR DESCRIPTION
**Pull request by terencehonles**
This is to help unblock Angular 13 support as mentioned in https://github.com/ng-bootstrap/ng-bootstrap/issues/4178#issuecomment-965018042. Opening a PR to see what the CI says since I believe this config is used by the CI.

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [ ] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by terencehonles** [comment]
Is playwright flaky? It looks like it passed on the default browser and firefox but not webkit. I don't believe that's related to this change.

**Comment by terencehonles** [comment]
I'm not able to run the e2e test locally on `master` either, so it looks like this is not related. It looks like playwright starts the browser but fails on `yarn demo:e2e`:


```
[1]   Components
[1]     ✗ should cover all components we have
[1]       - TypeError: Cannot read property '$$' of undefined
[1]           at /home/terence/projects/ng-bootstrap/demo/src/app/components/components.e2e-spec.ts:30:35
[1]           at <Jasmine>
[1]           at /home/terence/projects/ng-bootstrap/node_modules/tslib/tslib.js:117:75
[1]           at <Jasmine>
[1]           at Object.__awaiter (/home/terence/projects/ng-bootstrap/node_modules/tslib/tslib.js:113:16)
[1]           at UserContext.<anonymous> (/home/terence/projects/ng-bootstrap/demo/src/app/components/components.e2e-spec.ts:29:55)
[1]           at <Jasmine>

....

[1] **************************************************
[1] *                    Failures                    *
[1] **************************************************
[1] 
[1] 1) Components should cover all components we have
[1]   - TypeError: Cannot read property '$$' of undefined

...

[1] **************************************************
[1] *                     Errors                     *
[1] **************************************************
[1] 
[1] 1) Components accordion page
[1]   - TypeError: Cannot read property 'click' of undefined
```

Not sure if you have any idea why that might be happening.

I'm going to step out for a bit, and just a call out since you tagged this as for https://github.com/ng-bootstrap/ng-bootstrap/milestone/118 this is fine to have for v10 and will need to be updated to the v13 builders along with Angular 13 in https://github.com/ng-bootstrap/ng-bootstrap/pull/4182

**Comment by maxokorokov** [comment]
Interesting, my #4182 just passed fine in CI.
Marked it for v11 just to not forget it and to decide whether we want to replace ngx-build-plus with this

**Comment by terencehonles** [comment]
> Interesting, my #4182 just passed fine in CI. 

Well the errors above are just for me locally and not sure if I can fix them to get playwright to get further on the demo:e2e tests. It looks like the re-run you triggered may actually pass as far as the CI so it looks like the config is fine there.

**Review by maxokorokov — APPROVED** [review]
LGTM, thanks!
Let's switch to `@angular-builders`, it seems to be a much more popular project

**Comment by terencehonles** [comment]
@maxokorokov do you want me to create a PR against your branch for v13 or do you want to handle that? I can merge `master` or cherry pick the commit. If I don't here from you in a few hours when I'm back at my computer I can just use a merge strategy.

**Pull request merged**
