### PR TITLE
demo(fix): missing icon

### PR DESCRIPTION
**Pull request by kukac7**
add @FortAwesome/Font-Awesome icons
#2601

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
> It might be an overkill to have the whole fa just for one icon.

Yeh, I was thinking the same... I'm not sure how big fa is but it would probably slow down demo site load...

**Comment by maxokorokov** [comment]
~12Kb gzipped, I don't think it will slow the site load in any way, but still think it's an overkill.

There is an Angular API to include only one icon as an alternative: https://fontawesome.com/how-to-use/on-the-web/using-with/angular, but I'm not a fan of this either :)

**Comment by kukac7** [comment]
yes, I know it's a bit overkill.
I just wanted a simple method, and many people used it when it comes to icons. (including us)

yes, I know there is angular api, but for me it is not simpler and overkill than font.

**Comment by maxokorokov** [comment]
On a side note any `yarn.lock` changes shouldn't be a part of this PR

**Comment by kukac7** [comment]
sry, I fucked up. 😭

**Comment by pkozlowski-opensource** [comment]
@kukac7 thnx for the PR but we are going to merge #2624 instead as it doesn't require us to add / load new dependency.

Appreciate your contribution and time, though!

**Pull request closed without merging**
