### PR TITLE
demo: bootstrap 5.3 and dark mode

### LINKED ISSUE #4450: Bootstrap 5.3 and dark mode for docs
Bootstrap 5.3 alpha 1 was release https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/ so it will be nice to have a doc with dark mode to test the components.

[EDIT] Bootstrap 5.3 is out of alpha now https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/

### PR DESCRIPTION
**Pull request by bastienmoulia**
Fix #4450

### CODE REVIEW

**Comment by fbasso** [comment]
Thanks for your PR @bastienmoulia, we reviewed your PR, and it's quite good !

It's a quite old one, but is there a chance for you to have time to rebase and upgrade to the official 5.3 of Bootstrap ?

**Comment by bastienmoulia** [comment]
> Thanks for your PR @bastienmoulia, we reviewed your PR, and it's quite good !
> 
> It's a quite old one, but is there a chance for you to have time to rebase and upgrade to the official 5.3 of Bootstrap ?

Will try to take a look next week

**Comment by flavianoredressa** [comment]
Any news about it? bs 5.3 was released @bastienmoulia ?

**Comment by maxokorokov** [comment]
Closing as https://github.com/ng-bootstrap/ng-bootstrap/pull/4554 with this commit is merged. Thanks again!

**Pull request closed without merging**
