### PR TITLE
fix(rating): avoid inconsistent disabling

### PR DESCRIPTION
**Pull request by FFKL**
Hello! I've noticed that rating component has inconsistent disabling feature. It wasn't fully disabled. You can use tab for focusing readonly element. Also I reworked `disabled` property.

Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by FFKL** [comment]
@maxokorokov Hello! Can you review my PR?

**Review by maxokorokov — COMMENTED** [review]
Hey, @FFKL!

Thank you for the PR, however I don't quite understand what you're trying to achieve.

`Readonly` and `Disabled` are two distinct states:
1. `Disabled` → actually means disabled from the form point of view. Not focusable, not accesible to screen readers, not modifiable. Ex. like `<input disabled>`
2. `Readonly` → can de focused, the value can be read by screen readers, but the value can't be changed. Ex. like `<input aria-disabled="true">`

So I don't think what you're suggesting here is correct behavior.

P.S. We should probably update the `readonly` docs to be more explicit about it.

WDYT?

Cheers,
Max

**Comment by FFKL** [comment]
@maxokorokov Hi! Thanks for answering;) I get your point, but
1. `[attr.aria-disabled]': 'readonly ? true : null`. I think, It's strange behaviour. What about `aria-readonly` attribute? As I understand - `aria-disabled` is used here to replace the native `disabled` for custom input.
2. I can disable element focus only if I use `FormControl` but It can be necessary to disable element without `FormControl`.
I tried to fix these problems in my PR. Maybe I should improve it. What do you think?

**Comment by maxokorokov** [comment]
Will just drop a stackblitz with current behavior here → https://stackblitz.com/edit/angular-uhnyui-7lmv6p?file=src%2Fapp%2Frating-form.html

**Comment by FFKL** [comment]
@maxokorokov I don't understand you;)

**Comment by maxokorokov** [comment]
Fixed in #4603

**Pull request closed without merging**
