### PR TITLE
docs(table): add demo section about the table component

### PR DESCRIPTION
**Pull request by maxokorokov**
Adds the `Table` section to the demo site with an overview and several examples:

- basic table
- sorting
- pagination
- filtering
- async data service

cc @ExFlo, @pkozlowski-opensource, @benouat, @fbasso

### CODE REVIEW

**Comment by benouat** [comment]
@maxokorokov I am fine with these changes. you can merge. 🚀

**Comment by danielelic** [comment]
Hi @maxokorokov,

it seems that the example on
`https://ng-bootstrap.github.io/app/components/table/demos/sortable/stackblitz.html` doesn't work properly.
`https://ng-bootstrap.github.io/#/components/table/examples#sortable`

**Comment by maxokorokov** [comment]
@danielelic yeah, some stackblitzes are not working, so the workaround is :)
```sh
git clone https://github.com/ng-bootstrap/ng-bootstrap.git
yarn
yarn demo
```

**Comment by Perminus-Gaita** [comment]
Working stackblitz for the complete table : https://stackblitz.com/edit/ngbootstrap-table?file=app/app.module.ts
Working stackblitz for the table sorting : https://stackblitz.com/edit/ngbootstrap-table-sorting?file=app/app.module.ts

**Comment by benouat** [comment]
Thanks @Perminus-Gaita for these 2 stackblitzes. Unfortunately we can not use them as is. 😞

We dynamically generate all our stackblitzes from our demo source code. And our generator does not actually support **yet** this kind of demo (hence @maxokorokov > _I'll fix that later_).

**Pull request merged**
