### PR TITLE
feat(datepicker): add accessibility attributes on Datepicker

### LINKED ISSUE #1946: Datepicker: accessibility issues
### Bug description:
Accessibility issue
We noticed the following issues on the date picker widget:
- For the next/previous month buttons: there is no alternative text for screen readers and no tooltip on mouse over for the purpose of these buttons
- The days of the week are read in short format by screen readers: "Mon" instead of "Monday"
- Only the number is read by screen readers for the dates in the calendar: "1" instead of "Monday 1 September"
- After selecting a date, the selected date should be conveyed to screen reader users. This could be achieved by setting the focus back to the input field as raised in #1934 

Tested with NVDA/Firefox and JAWS/IE

### Link to minimally-working plunker that reproduces the issue:
Date picker in a pop-up
https://ng-bootstrap.github.io/#/components/datepicker/examples

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: angular 4.4.6

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-beta.2

### PR DESCRIPTION
**Pull request by ExFlo**
Closes #1946

Before submitting a pull request, please make sure you have at least performed the following:

 - [] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [] built and tested the changes locally.
 - [] added/updated any applicable tests.
 - [] added/updated any applicable API documentation.
 - [] added/updated any applicable demos.

### CODE REVIEW

**Comment by brunano21** [comment]
Any news on this PR?

**Comment by maxokorokov** [comment]
@brunano21 we'll merge #2270 to close #1716 first. And then will have another PR with simpler version without async stuff and aria active descendant, just with aria labels.

This was a perfectly working PR, but after testing with various screen readers, simpler solution also works fine. I'll leave this one open for now though.

**Comment by benouat** [comment]
@pkozlowski-opensource  @maxokorokov now that #2270 #2319 and #2345 have landed I think we should clean backlog by closing this one.

**Comment by pkozlowski-opensource** [comment]
Thnx @benouat

**Pull request closed without merging**
