### PR TITLE
demo(pagination): add pagination horizontal alignment demo

### PR DESCRIPTION
**Pull request by ktriek**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

The alignment of the pagination component with flexbox utilities start, center, end https://getbootstrap.com/docs/4.0/components/pagination/#alignment.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Is it really needed? Why not add a CSS class on a pagination itself as described in https://github.com/ng-bootstrap/ng-bootstrap/issues/1795#issuecomment-325943790?

**Comment by ktriek** [comment]
@pkozlowski-opensource thanks, my bad, I didn't pay attention to #1795, In  case you don't want want to change the pagination API I think it would be beneficial to add  this case to the pagination documentation.
I can make the changes to the PR to leave just the demo part.

**Comment by pkozlowski-opensource** [comment]
> I can make the changes to the PR to leave just the demo part.

Yep, this would be useful, please do. Thank you!

**Comment by pkozlowski-opensource** [comment]
Merged, thnx so much for adding this demo, much appreciated!

**Pull request closed without merging**
