### PR TITLE
chore(progressbar): upgrade to 4.0.0-alpha.6

### PR DESCRIPTION
**Pull request by jnizet**
refs #1178

### CODE REVIEW

**Comment by jnizet** [comment]
This is one of probably many PRs allowing to upgrade to alpha.6. Maybe we shoul make an alpha-6 branch, and merge all those individual PRs to this alpha-6 branch, to finally merge the alpha-6 branch to master when everything is ready.

**Comment by pkozlowski-opensource** [comment]
Thnx @jnizet ! +1 for a separate branch - IMO we should first cut a release with a fix we've got in master + freezing BS version in plunkers (#1179). Then have a branch where we could update to bs.alpha.6 (and potentially angular 2.4.x as well as there are some APIs that would allow us to simplify modal and some other impls)

**Comment by jnizet** [comment]
Branch created: bootstrap-alpha.6-upgrade.

I'll re-target this PR to the bootstrap-alpha.6-upgrade branch.

**Comment by pkozlowski-opensource** [comment]
merged as 7e4af877f89c50b947ee2cd108677a6538be6e50

**Pull request closed without merging**
