### PR TITLE
feat(pagination):  allow default size for pagination

### LINKED ISSUE #3816: NgbPagination: Size 'md' missing from type
### Bug description:
Pagination.ts states:
```
 /**
     * The pagination display size.
     *
     * Bootstrap currently supports small and large sizes.
     */
    size: 'sm' | 'lg';
```

But the default size is actually 'md' which is a supported size.

So I am not allowed to set the [size] to 'md', without getting errors like this:

_Type 'string' is not assignable to type '"sm" | "lg"'._

### Solution

Add 'md' size to  NgbPagination.size type

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 10
ng-bootstrap: 7
Bootstrap: 4.5

### PR DESCRIPTION
**Pull request by umernaeem217**
Fixes #3816

### CODE REVIEW

**Comment by umernaeem217** [comment]
@maxokorokov Please check the PR.

**Review by maxokorokov — CHANGES_REQUESTED** [review]
Hey, thanks for the PR!

- please add tests as described here, for example → https://github.com/ng-bootstrap/ng-bootstrap/issues/3816#issuecomment-843278374
- could we stick to `'sm' | 'lg' | string` as we do in other components for consistency?

**Comment by umernaeem217** [comment]
@maxokorokov  Please check I have updated. Can I help you in maintaining this repository?

**Comment by peterblazejewicz** [comment]
shouldn't this be simply:
```ts
size?: 'sm' | 'lg' | undefined;
```

**Comment by maxokorokov** [comment]
@umernaeem217 I'm sorry, I've re-read the inital issue and the actual problem was with 'null' value... So your initial commit was good, actually. I've opened #4319 where I cherry-picked it, so I'll close this one.

**Pull request closed without merging**
