### PR TITLE
demos: 'See component on bootstrap website' link in sidebar

### PR DESCRIPTION
**Pull request by benouat**
I change a bit the configuration of all eligible components to embed the url to the corresponding Bootstrap documentation page.

I added it to the table of content sidebar/popover menu, whatever the selected tab (it will appear in Overview/Examples and API)

I rely on `data` property in routes configuration for each component module.

<details>
  <summary>See screenshots</summary>

image
---
image
---
image
</details>

### CODE REVIEW

**Comment by benouat** [comment]
A more global overview

image

**Comment by benouat** [comment]
What about `Orignal Accordion` as text (with obviously the Bootstrap icon) ?

**Comment by benouat** [comment]
Thanks @maxokorokov for the feedback
Here is the final version

image

**Comment by peterblazejewicz** [comment]
image
Maybe that way ('See on getbootstrap.com" [See accordion component on getbootstrap.com])
See on is succinct, will fit the shortcut purpose with obvious content I think

**Comment by benouat** [comment]
thanks @peterblazejewicz, nonetheless I think I'd like to keep the component name in the link

**Pull request merged**
