### PR TITLE
Datepicker/replace shift with alt

### PR DESCRIPTION
**Pull request by gpolychronisAmadeus**
@benouat 
@maxokorokov 

Please review

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Random note for `chore(datepicker): replace shift with alt` -> the change in this commit is definitively not `chore` - it is either feature of a fix...

**Comment by benouat** [comment]
@pkozlowski-opensource 👍
It should be a `fix`. We did it wrong in the first place a long time ago.

@gpolychronisAmadeus could you please update the commit message please, and force push ?

**Comment by gpolychronisAmadeus** [comment]
> 
> 
> @pkozlowski-opensource 👍
> It should be a `fix`. We did it wrong in the first place a long time ago.
> 
> @gpolychronisAmadeus could you please update the commit message please, and force push ?

Done

**Comment by maxokorokov** [comment]
@gpolychronisAmadeus could you please not base new PRs on other commits that are reviewed in other PRs? 

It's hard to keep track of what should be merged where and to review. Like in this case changes to `bg-light` are from other PR and shouldn't be a part of this.

**Comment by gpolychronisAmadeus** [comment]
> 
> 
> @gpolychronisAmadeus could you please not base new PRs on other commits that are reviewed in other PRs?
> 
> It's hard to keep track of what should be merged where and to review. Like in this case changes to `bg-light` are from other PR and shouldn't be a part of this.

New PRs are based on older ones to work properly, but I will see what I can do.

**Pull request closed without merging**
