### PR TITLE
feat: upgrade to Angular 16

### PR DESCRIPTION
**Pull request by jnizet**
- upgrade dependencies versions
- removed a re-generate yarn.lock
- fix formatting due to prettier upgrade
- fix deprecations in schematics
- remove usage of getFileContent (which doesn't exist anymore) in schematics spec
- revert @types/node dependency to 16.x (because the 17 version, which I guess is unstable caused a typing error)
- fix schematics test to apply the version 16 of the project generation and check in the right file that localize is being added to the project

The build currently fails when running the playwright tests, with the following error message:

```
[WebServer] This version of CLI is only compatible with Angular versions ^15.0.0,
but Angular version 16.0.0 was found instead.
```

I guess I get this error because of the custom webpack builder, which hasn't been upgraded to Angular 16 yet.

Remaining work:

- make the complete build pass
- change documentation 
- mark some inputs as required (but I don't thing there are many)

### CODE REVIEW

**Comment by md13381** [comment]
Custom webpack just added the beta version for v16 so might now work with updated dependency

**Comment by gnegrini** [comment]
Hey guys, I appreciate your work on this! At the moment, this is the only package holding my team to migrate to Angular 16, hope to have it soon!

**Comment by jnizet** [comment]
@gnegrini I'm using ng-bootstrap with Angular 16 since Angular 16 came out. All you need to do is to tell npm to not care about the version mismatch. Or to use yarn, which just prints a warning in case of version mismatch.
Angular is backward-compatible, and even though the current version has not been formally tested with Angular 16, it works just fine.

That said, I sure hope that this PR is merged soon and that a new release comes out.

**Comment by gnegrini** [comment]
> @gnegrini I'm using ng-bootstrap with Angular 16 since Angular 16 came out. All you need to do is to tell npm to not care about the version mismatch. Or to use yarn, which just prints a warning in case of version mismatch. Angular is backward-compatible, and even though the current version has not been formally tested with Angular 16, it works just fine.
> 
> That said, I sure hope that this PR is merged soon and that a new release comes out.

Awesome! We have started migrating one project using --legacy-peer-deps on npm install, and so far so good. But we are afraid components from other projects might break.  Also, the #4498 is tagged with "breaking change", so there I wonder... Did you experience any component break in your projects?

**Comment by jnizet** [comment]
> Did you experience any component break in your projects?

No. As I said, it works just fine.

Using Angular 16 in ng-bootstrap is a breaking change because you won't be able to use it with a version of Angular older than 16, but the reverse isn't true: Libraries built for Angular 15 should normally be compatible out of the bow with  Angular 16.

**Comment by md13381** [comment]
Can confirm as well i have had no issues with using the current version in angular 16

**Review by maxokorokov — APPROVED** [review]
LGTM, thanks, @jnizet.
Will do RC release ASAP.

**Pull request merged**
