### PR TITLE
fix: add escape character for unicode identification

### PR DESCRIPTION
**Pull request by Atifarooq**
Unable to set an integer as the ng-panel id #4066
https://github.com/ng-bootstrap/ng-bootstrap/issues/4066

Fixed: [Helping Link](https://mathiasbynens.be/notes/css-escapes)

### CODE REVIEW

**Comment by Atifarooq** [comment]
I have fixed it and generate PR, you guys can have look and approve it
Issue Number: [4066](https://github.com/ng-bootstrap/ng-bootstrap/issues/4066)

@pkozlowski-opensource / @maxokorokov

**Comment by maxokorokov** [comment]
Hmm, wasn't it fixed in #4196 ?

**Comment by maxokorokov** [comment]
Hmm, wasn't it fixed in #4196 ?

**Comment by Atifarooq** [comment]
That was different kind of issue, In this PR addressing the issue when user use number as accordion ID and it thow error in console

**Review by maxokorokov — CHANGES_REQUESTED** [review]
Hey, thanks for the PR!

- [ ] it looks like you've just added a function that's not used anymore ? 
- [ ] please add unit tests

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.

**Pull request closed without merging**
