### PR TITLE
demo: prevent api doc columns from clobbering each other

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This is an attempt at solving #476

I'm not a big fan of this change but this is the best I can think of right now. Maybe it will trigger a better idea...

### CODE REVIEW

**Comment by maxokorokov** [comment]
Argh, thought was commenting here... See the screenshot in #476 

```html
<table class="table table-sm table-hover">
  <tbody>
    <tr *ngFor="let input of apiDocs.inputs">
      <td class="col-md-3"><code>{{input.name}}</code></td>
      <td class="col-md-9">
        <div><i>Type: </i><code>{{ input.type }}</code></div>
        <div><i>Default value: </i>{{input.defaultValue || '-'}}</div>
        <div style="margin: 10px 0">{{ input.description }}</div>
      </td>
    </tr>
  </tbody>
</table>
```

and would throw away the header completely...

**Comment by pkozlowski-opensource** [comment]
> and would throw away the header completely...

We need to keep some consistency between inputs and outputs. If we throw it away we should do it for both or none.

**Comment by maxokorokov** [comment]
would have also probably added `<code>` for the default value, unless it's `-`

**Comment by pkozlowski-opensource** [comment]
I've pushed an update to this PR based on @maxokorokov ideas. I've also added a check around default value so we display it only when there is one. This limits amount of unused blank space.

I start to like it!

api_doc_changes

**Comment by pkozlowski-opensource** [comment]
@icfantv I've pushed this one as I think it is best we've got right now. You had some ideas about using muted text which I didn't quite get so please send a follow up PR(s) if you see how to improve things. Thnx!

**Pull request closed without merging**
