### PR TITLE
feat(popover): update popover position on mousemove (#3575)

### PR DESCRIPTION
**Pull request by gpolychronis**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by gpolychronis** [comment]
@benouat @maxokorokov 
Please review

**Comment by fbasso** [comment]
I'm afraid about performance issues if the positioning is re-calculated on each mousemove.

Moreover, we already have performance issues opened because of the ngZone.onStable usage, and the direction (waiting for some decisions and code reviews for now) is more to remove onStable to use scroll or resize evens to re-positions the popups. So I'm not sure this is the fix to do.

Waiting for @benouat and @maxokorokov to see what they think about it.

**Comment by benouat** [comment]
I am aligned with @fbasso I don't think it's a good idea.

**Comment by gpolychronis** [comment]
The issue is that the popover should follow the resizing. Inevitably this means triggering on mouseover.
@fbasso @benouat How should I solve the problem, hmm? Any thoughts on that?

**Comment by gpolychronis** [comment]
There already an issue on that.

**Comment by benouat** [comment]
Have a look at #3579 to follow updates

**Pull request closed without merging**
