### PR TITLE
fix(datepicker): change trigger event for NgbInputDatepicker

### PR DESCRIPTION
**Pull request by PerfectPixel**
Changes the trigger event in NgbInputDatepicker for manual date change from `change` to `input`as discussed in #1225.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@PerfectPixel thnx for the PR, it looks good. One question though - did you test it on IE10/11 and / or Edge? I recall that there are some issues with how the `input` event is handled in those browsers and I would like to verify that we are not breaking code on those browsers (existing unit tests won't catch those issues, unfortunately...)

**Comment by PerfectPixel** [comment]
@pkozlowski-opensource ok there is a rub. [This line](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/datepicker-input.ts#L190) causes the following behaviour:

1. User types "2017"
2. "2" is not a valid `NgbDate` -> `this._model = null`, therefore, `_onChange = '2'` and the input is overwritten with `null` by `_writeModelValue(null)`
3. "0" becomes the first number again as the input was reset with null.
4. and so on...

Here is a gif where I am typing numbers randomly.
untitled

The easiest solution is to uncomment [this line](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/datepicker/datepicker-input.ts#L190). However, there are a few changes in behaviour:

1. Typing a year + month and press enter no longer autocompletes the input to year + month + 1st of month (although the model stays the same).
2. It is now possible to enter letters (a-zA-Z etc.) into the input.

**Comment by PerfectPixel** [comment]
@pkozlowski-opensource have a look at my last commit. This fixes the input. Also, it mitigates the first issue as I introduced a change event that updates the view with the model enabling autocomplete of the day once again. The 2nd and 3rd issues are also happening in the original version just on a different event.

**Comment by pkozlowski-opensource** [comment]
@PerfectPixel it all looks good to me! We've got a big PR for date picker in-flight (keyboard navigation) so I'm going to wait with merging till the end of the week (so other PR can land first).

Thnx!

**Comment by pkozlowski-opensource** [comment]
@PerfectPixel the other PR I've mentioned just landed so we can get in this one. Would you mind rebasing so we can land your PR?

**Comment by PerfectPixel** [comment]
Sure, I'll have a look at it tonight

**Comment by PerfectPixel** [comment]
@pkozlowski-opensource all done :-)

**Pull request closed without merging**
