### PR TITLE
chore: update to Bootstrap 4.1

### PR DESCRIPTION
**Pull request by bastienmoulia**
Add bootstrap 4.1 dependency for 2.0 milestone.

Add a table with version compatibility in the readme.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@bastienmoulia I was discussing this today with @maxokorokov and I think that we can leave 4.0.0 as a minimal _required_ Bootstrap CSS as all the releases so far work with both 4.0.0 _and_ 4.1.0.

WDYT?

**Comment by bastienmoulia** [comment]
@pkozlowski-opensource It's true, just don't forget during the release to change the package.json `"bootstrap": "4.0.0"`in `"bootstrap": "^4.0.0"` and maybe the readme `tested with 4.1.0`.

**Comment by pkozlowski-opensource** [comment]
> It's true, just don't forget during the release to change the package.json 

Well, I would much prefer that I don't have to remember about those things :-) 

In any case we can reasonably use / test only with one version of Bootstrap CSS so I would prefer that we are consistent with what we use and what we claim in our package.json.

I think that we should merge it when we are ready to require Bootstrap 4.1 from our users (and this is independent from the Angular version). Marking it as a breaking change.

**Comment by pkozlowski-opensource** [comment]
As commented above today ng-bootstrap works with Bootstrap CSS `^4.0.0`. In practice it means that our library works perfectly with _any_ version of Bootstrap CSS. I see it as a good thing since bumping up _minimal_ Bootstrap CSS dependency is a breaking change.

For now we will stay with requirement for the minimal Bootstrap CSS version being `4.0.0`. We will update it only when we see there is a bug affecting ng-bootstrap that was fixed in any of 4.x versions.

Thnx for the PR but we are going to keep it as-is for now.

**Comment by mendeza** [comment]
Thank you, it is good to understand the project stance clearly.

**Pull request closed without merging**
