### PR TITLE
fix(timepicker): handle undefined state when meridian is true

### PR DESCRIPTION
**Pull request by shibulijack**
Fixes #[1106](https://github.com/ng-bootstrap/ng-bootstrap/issues/1106)

### CODE REVIEW

**Comment by jedijashwa** [comment]
I downloaded and built this change and it fixed the issue on my machine and did not break any other functionality.

**Comment by pkozlowski-opensource** [comment]
I would _really_ like to see a plunker with a reproduce scanario before we move forward on this. Without a reproduce scenario we don't understand what is going on exactly so we can't add a test (and this PR is missing a test so there is zero gurantee that we are not going to re-introduce regressions in the future). 

@shibulijack @jedijashwa since you are seeing this pb on your side could you please distill it in a plunker and add a test to this PR?

**Comment by jedijashwa** [comment]
@pkozlowski-opensource it will be a while but I can if @shibulijack cannot.

**Comment by shibulijack** [comment]
@pkozlowski-opensource I tried to reproduce the scenario in a Plunker, but couldn't. My project is scaffolded using Angular Cli, so it uses Webpack instead of System JS. How can I replicate this using Plunker?

**Comment by jedijashwa** [comment]
My project is using system js but I pulled out the timepicker stuff, hence it taking so long for me to set up a plunker

**Comment by pkozlowski-opensource** [comment]
@shibulijack I've just spent 1/2h trying to reproduce the problem that this PR is supposed to solve but couldn't - was trying all kind of crazy input combinations and couldn't break it. As such I'm going to close this PR since it doesn't merge cleanly, we don't have, reproduce scenario etc.

More than happy to re-visit as soon as someone can reproduce the original issue in a plunker. Thnx!

**Pull request closed without merging**
