### PR TITLE
Add support of Hebrew calendar in datepicker

### PR DESCRIPTION
**Pull request by semion1956**
See issue #1667 .

### CODE REVIEW

**Comment by tomerm** [comment]
@pkozlowski-opensource , @icfantv , @maxokorokov FYI.

**Comment by pkozlowski-opensource** [comment]
Awesome, thank you! We are going to review this PR in the coming days!

**Comment by adir01** [comment]
Can you please review this PR ?

**Comment by pkozlowski-opensource** [comment]
@adir01 sorry it is taking a bit of time, we've been busy with beta.0 release. Will get to the datepicker + calendars PR next week. Thnx again for the PR, it is much appreciated. And once again, sorry for the delay...

**Comment by maxokorokov** [comment]
I'll cherry-pick changes related to the calendar implementation and tests and open a separate PR with everything rebased.

**Comment by maxokorokov** [comment]
Cherry-picked calendar commit from this PR and opened #2606

**Pull request closed without merging**
