### PR TITLE
demo(typeahead): add form-control class to inputs

### PR DESCRIPTION
**Pull request by maxokorokov**
Minor fix → adding `form-control` class to demos with typeahead to inputs

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I'm not sure... I think I like the version before this change better... Let's see what others think...

**Comment by maxokorokov** [comment]
It looks horrifying in IE :) 
It shouldn't fill the whole width probably though

**Comment by pkozlowski-opensource** [comment]
> It shouldn't fill the whole width probably though

Yep, that's my point. I was briefly checking if we can make it smaller without too much pain. Size?

**Comment by maxokorokov** [comment]
```javascript
@Component({
  ...
  styles: [`.form-control { width: 300px; }`]
})
```

screen shot 2016-07-28 at 19 23 52

**Comment by pkozlowski-opensource** [comment]
Yep, if you could update the PR so an input gets smaller size this would be great.

**Comment by maxokorokov** [comment]
done

**Pull request closed without merging**
