### PR TITLE
refactor(carousel): reimplement with observables and clean up API

### PR DESCRIPTION
**Pull request by maxokorokov**
Work in progress

Two main goals pursued by this:
- check what it would be like with rxjs
- clean up the huge unintentionally public API

Things to check:
- [x] protractor tests
- [x] SSR

See #858 for SSR

### CODE REVIEW

**Comment by maxokorokov** [comment]
Fixed SSR by injecting the `@Inject(PLATFORM_ID)`

**Comment by maxokorokov** [comment]
Tested with the new setup for e2e tests and adding `runOutsideAngular` seems to fix the protractor issues as well

**Comment by pkozlowski-opensource** [comment]
> Tested with the new setup for e2e tests and adding runOutsideAngular seems to fix the protractor issues as well

Awesome!

**Comment by pkozlowski-opensource** [comment]
LGTM!

**Pull request closed without merging**
