### PR TITLE
fix(alert): new css class for close button

### PR DESCRIPTION
**Pull request by nbittich**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Review by maxokorokov — APPROVED** [review]
LGTM!

@fbasso, could you take a look too, please? Please merge if OK.
I've added the reference to it in the main BS5 issue

**Comment by maxokorokov** [comment]
P.S. We're going to need the same kind of PR for the toast, if you're up to it. And thanks @nbittich for helping out.

**Comment by nbittich** [comment]
> P.S. We're going to need the same kind of PR for the toast, if you're up to it. And thanks @nbittich for helping out.

Sure I will have a look to the toast this evening after work. I was working on  the accordion yesterday, did something like below, unfortunately it breaks the "custom" one in the demo. Can look at it also if needed.

```
    <ng-template #t ngbPanelHeader let-panel>
    <div class="accordion-header">
      <button class="accordion-button" [ngbPanelToggle]="panel">
        {{panel.title}}<ng-template [ngTemplateOutlet]="panel.titleTpl?.templateRef"></ng-template>
      </button>
    </div>
    </ng-template>
    <ng-template ngFor let-panel [ngForOf]="panels">
      <div [class]="'accordion-item ' + (panel.cardClass || '')">
        <div role="tab" id="{{panel.id}}-header" [class]="' ' + (panel.type ? 'bg-'+panel.type: type ? 'bg-'+type : '')">
          <ng-template [ngTemplateOutlet]="panel.headerTpl?.templateRef || t"
                       [ngTemplateOutletContext]="{$implicit: panel, opened: panel.isOpen}"></ng-template>
        </div>
        <div id="{{panel.id}}" role="tabpanel" [attr.aria-labelledby]="panel.id + '-header'" [class]="'accordion-collapse'"
             *ngIf="!destroyOnHide || panel.isOpen || panel.transitionRunning">
          <div class="accordion-body">
               <ng-template [ngTemplateOutlet]="panel.contentTpl?.templateRef || null"></ng-template>
          </div>
        </div>
      </div>
    </ng-template>

**Comment by maxokorokov** [comment]
@nbittich, we'd like to deprecate existing accordion and create a new one based on directives (similar to navs) → #3898

Not sure/haven't looked yet what has to be done for the existing one:
- keep markup and classes as-is, but add custom css in ng-bootstrap
- or use new accordion classes

**Pull request merged**
