### PR TITLE
chore(demo): add fine-grained analytics

### LINKED ISSUE #401: Demo site additions
- [x] analytics
 - [x] basic analytics
 - [x] fine-grained analytics
- [x] "tweet me" button

### PR DESCRIPTION
**Pull request by icfantv**
* add route tracking
* add some basic site usage tracking

Fixes #401

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@icfantv thnx for the PR. I had a deeper look and I would like to clarify few items before that gets in:
* [ ] I don't think that tracking of code opening works - at least I can't see any evidence of it working
* [ ] it behaves in a wired way for hasbang URLs - I've got an impression that we've got 2 events for each page navigation - hasbang one and also a non-hasbang one (?)
* [ ] I wonder if Angularytics buys us enough to justify an additional dependency - will look more into it.

Also, could you please remove twitter button from this PR and open a separate one? Small PRs are soooo much easier to review / merge!

**Comment by icfantv** [comment]
removed twitter to PR #497.

**Comment by icfantv** [comment]
confirmed that opening the tracking code works - check the network stack in the browser.

**Comment by icfantv** [comment]
I'm following the GA request network calls and it is working fine for route navigation with the hashbang URLs.  I.e., I'm only seeing one request being made.

I believe it is imperative to understand how our users are using our site.  Tracking route navigation gives us insight into what components are being used the most and tracking certain other features gives us insight as to their use.  Clearly, it's easy to get totally carried away and put them everything, but that's not necessary here.

**Comment by pkozlowski-opensource** [comment]
@icfantv I've landed this with a change - I've removed part that was tracking clicks on demo sources as it was reported incorrectly. I will open a new issue for more tracking.

**Comment by icfantv** [comment]
@pkozlowski-opensource sounds good.  Thanks.  Still not sure why it's getting reported as a route change...

**Comment by pkozlowski-opensource** [comment]
> Still not sure why it's getting reported as a route change...

Me neither. Maybe we should just hand-roll those tracking scripts so we can understand what is going on...

**Pull request closed without merging**
