### PR TITLE
fix(buttons): don't interfere with 'active' class

### LINKED ISSUE #557: Buttons: NgbRadioLabel directive is too "agressive"
The `NgbRadioLabel` as implemented today prevents checkbox demo from working correctly. It is implementation is very simple:

```typescript
@Directive({selector: 'label.btn', host: {'[class.active]': 'checked'}})
export class NgbRadioLabel {
  @Input() checked: boolean;
}
```

But if we move to NgModules this directive gets activated on all labels with the `btn` class (quite common scenario). And it can mess up scenarios like this:

 ```html
  <label class="btn btn-primary" [class.active]="model.left">
    <input type="checkbox" [(ngModel)]="model.left"> Left (pre-checked)
  </label>
```

In this scenario ` [class.active]="model.left"` will be overridden by the NgbRadioLabel directive and will never take effect. We can't remove `active` label when the directive is not used / manipulated from outside.

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #557

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@maxokorokov would you mind reviewing this one?

**Comment by wesleycho** [comment]
LGTM

**Comment by Foxandxss** [comment]
LGTM as well.

**Comment by maxokorokov** [comment]
@pkozlowski-opensource I'm late, but LGTM too

**Pull request closed without merging**
